/* The advertiser's landing page, and the invitation at /signin. */

const en = {
  nav: { flow: 'How it works', packages: 'Rates', reporting: 'Reporting' },
  ads: [
    { label: 'Now playing · Bottom banner', brand: 'Iron Rose Gym', detail: 'First class free · two doors down' },
    { label: 'Now playing · Full screen', brand: 'Freedom Cycles', detail: 'Free tune-up · two blocks north' },
    { label: 'Now playing · Short video', brand: 'Ninth Street Books', detail: '10% off with your receipt' },
  ],
  hero: {
    title1: 'Show up where your neighbors ',
    title2: 'already look.',
    lede: (floor: string) => `Buy a slice of the menu board at a shop in your neighborhood. Your ad plays while someone is standing at the counter, already deciding what to spend money on. Pick the county, the area and the hours across Salt Lake, Utah and Cache, from ${floor} a minute.`,
    build: 'Build your campaign',
    orContact: 'Or have us set it up',
    foot: 'No account needed, and none to create: we are in pilot and not open for volume yet. Price it, put your artwork on a real board, then send it to us when you want it to run.',
  },
  boards: {
    title: 'See it running.',
    lede: 'Two boards on the network. Your spot sits inside the one thing everyone in the room is already reading, at the exact moment they are deciding what to spend money on.',
  },
  network: {
    title: 'Book one block, or the whole county.',
    lede: (minutes: string) => [
      'Shops are joining the network every day, and booking one gives you access to one of the most intimate marketing experiences available: your ad on the counter your neighbours are already standing at. ',
      'Salt Lake County', ', ', 'Utah County', ' and ', 'Cache County',
      ` are open now, every board holding about ${minutes} minutes of ad time a week. Take one shop near your door, a neighborhood, or all three counties at once.`,
    ],
    caption: 'The kinds of shops AdBite is opening with, each in its own town. The pilot runs across Salt Lake, Utah and Cache counties.',
    onTheNetwork: 'On the network',
    shopsCounties: (shops: number, counties: number) => `${shops} shops · ${counties} counties`,
    mapAlt: (name: string, kind: string, city: string, county: string) => `A map of the United States with Utah drawn large over it, marking the shop whose turn it is. Showing ${name}, ${kind} in ${city}, ${county}.`,
    counties: { cache: 'Cache County', saltlake: 'Salt Lake County', utah: 'Utah County' },
    kinds: {
      Diner: 'Diner', Taqueria: 'Taqueria', Barbershop: 'Barbershop', Bakery: 'Bakery',
      'Chicken shop': 'Chicken shop', Café: 'Café', Deli: 'Deli', Salon: 'Salon',
      Pizzeria: 'Pizzeria', 'Nail salon': 'Nail salon',
    } as Record<string, string>,
  },
  packages: {
    title: 'Four shapes. Priced on two things.',
    ledeBefore: 'How much of the board your ad takes, and ',
    ledeWhen: 'when',
    ledeAfter: ' it runs. A strip under the menu is the cheapest thing we sell. Blanking the whole board costs the most, because while it runs the shop’s own menu is gone. Peak is lunch and dinner, when there is a queue; the afternoon is about half.',
    perMin: '/ min',
    slabFoot: (tier: string, minutes: string) => `${tier} · from, for a bottom banner · ${minutes} min free`,
    look: {
      banner: { sell: 'A strip under the menu, in view the whole time someone is deciding what to order.', note: 'The least of the board, so the least to pay.' },
      rail: { sell: 'The right third, top to bottom. Holds the screen continuously without ever hiding the menu.', note: 'More of the board than a strip, and priced for it.' },
      full: { sell: 'The whole board for your turn in the rotation. Nothing else on it.', note: 'The menu is gone while it runs, which is what you are paying for.' },
      video: { sell: 'Fifteen muted seconds in the full-screen slot. Motion in a room where nothing else moves.', note: 'Billed per play, not per minute. You buy a count of runs.' },
    },
    peakPer: (unit: string) => `peak, per ${unit}`,
    offPeak: (rate: string) => `${rate} off-peak`,
    payPlays: 'You pay for plays that ran',
    payMinutes: 'You pay for minutes shown',
    buildOne: 'Build one',
    foot: 'Every price above is what you pay. There is no auction, no bidding against a national brand for the shop on your corner, and no rate that moves because of who else showed up that week.',
  },
  reporting: {
    eyebrow: 'The dashboard, not a drawing of it',
    title: 'Know exactly where your money went.',
    ledeBefore: 'Every screen below is the real builder and the real report, captured from the product. You can open the ',
    ledeLink: 'dashboard',
    ledeAfter: ' and build a campaign right now, without an account.',
    foot: 'AdBite bills on two things and reports both: how many times your ad played, and the minutes it was on screen, split peak and off-peak, per shop. Anything worked out rather than counted — heads past the board, cost per thousand — is labelled as such on the screen it appears on. There are no impressions here, and no reach estimates dressed up as measurements.',
  },
  advertise: {
    eyebrow: 'Pilot access',
    title: 'Want to advertise?',
    lede: 'Put your details in and we will get you onto the pilot. A person reads it, finds the boards that suit what you sell, and writes back with what is open and what it would cost.',
    form: {
      business: 'Business type',
      businessPlaceholder: 'Florist, dentist, gym…',
      where: 'Where you are',
      wherePlaceholder: 'Provo, Sandy, Logan…',
      budget: 'Weekly budget',
      budgetPlaceholder: 'Choose a range',
      message: 'What you would say',
      messagePlaceholder: 'Free tune-up, two blocks north',
      email: 'Your email',
      emailPlaceholder: 'you@yourbusiness.com',
      submit: 'Get me on the pilot',
      thanks: 'Thanks, we’ll be in touch',
      note: 'We’ll come back with the boards that suit you and what a week on them costs.',
    },
  },
  signin: {
    eyebrow: 'Ramping up volume',
    title: 'Target your city. Or just your neighborhood.',
    lede: 'We are adding screens and bringing advertisers on every week. Tell us where you are and what you would run, and we will get you onto the boards closest to your customers.',
    points: [
      'Pick the city, the neighborhood and the hours. Your ad runs on those boards and nowhere else',
      'No auction. The rate card is the rate, and it does not move because someone with a bigger budget turned up that week',
      'You pay for what actually ran, by the minute or by the play. An ad that never played is never billed',
    ],
    ratherWrite: 'Would rather just write?',
    panelTitle: 'Tell us where you are',
    runningAShop: 'Running a shop instead?',
    joinShop: 'Join the shop waitlist',
    done: {
      title: 'You’re on the list.',
      text: 'We will find the nearest board to you and come back with what is open on it and what it would cost. A person writes back, not an auto-responder.',
      build: 'Build your ad while you wait',
    },
    form: {
      name: 'Your name',
      namePlaceholder: 'Sam Ortega',
      business: 'Business',
      businessPlaceholder: 'Iron Rose Gym',
      where: 'Where you are',
      wherePlaceholder: 'Provo, Sandy, Logan…',
      email: 'Email',
      emailPlaceholder: 'you@yourbusiness.com',
      about: 'What you would want to run',
      aboutPlaceholder: 'A banner for the lunch rush, two blocks north',
      submit: 'Get me on a board',
      note: (mail: string) => `Goes straight to ${mail}, where a person reads it. Nothing is charged and you are not committing to anything.`,
    },
  },
};

const es: typeof en = {
  nav: { flow: 'Cómo funciona', packages: 'Tarifas', reporting: 'Reportes' },
  ads: [
    { label: 'En pantalla · Franja inferior', brand: 'Iron Rose Gym', detail: 'Primera clase gratis · dos puertas más allá' },
    { label: 'En pantalla · Pantalla completa', brand: 'Freedom Cycles', detail: 'Afinación gratis · dos cuadras al norte' },
    { label: 'En pantalla · Video corto', brand: 'Ninth Street Books', detail: '10% de descuento con tu recibo' },
  ],
  hero: {
    title1: 'Aparece donde tus vecinos ',
    title2: 'ya están mirando.',
    lede: (floor: string) => `Compra una parte del tablero de menú de un negocio de tu vecindario. Tu anuncio se muestra mientras alguien está parado en el mostrador, decidiendo en qué gastar. Elige el condado, la zona y las horas en Salt Lake, Utah y Cache, desde ${floor} por minuto.`,
    build: 'Crea tu campaña',
    orContact: 'O deja que la armemos por ti',
    foot: 'No necesitas cuenta, y no hay ninguna que crear: estamos en piloto y todavía no abrimos en volumen. Calcúlala, pon tu arte en un tablero real, y mándanosla cuando quieras que se muestre.',
  },
  boards: {
    title: 'Míralo funcionando.',
    lede: 'Dos tableros de la red. Tu anuncio va dentro de lo único que todos en el local ya están leyendo, justo en el momento en que deciden en qué gastar.',
  },
  network: {
    title: 'Reserva una cuadra, o el condado entero.',
    lede: (minutes: string) => [
      'Cada día se suman negocios a la red, y reservar uno te da acceso a una de las experiencias de marketing más cercanas que existen: tu anuncio en el mostrador donde tus vecinos ya están parados. ',
      'El condado de Salt Lake', ', ', 'Utah', ' y ', 'Cache',
      ` ya están abiertos, y cada tablero tiene cerca de ${minutes} minutos de tiempo de anuncios a la semana. Toma un negocio cerca de tu puerta, un vecindario, o los tres condados a la vez.`,
    ],
    caption: 'El tipo de negocios con los que abre AdBite, cada uno en su propio pueblo. El piloto corre en los condados de Salt Lake, Utah y Cache.',
    onTheNetwork: 'En la red',
    shopsCounties: (shops: number, counties: number) => `${shops} negocios · ${counties} condados`,
    mapAlt: (name: string, kind: string, city: string, county: string) => `Un mapa de Estados Unidos con Utah dibujado en grande encima, marcando el negocio en turno. Mostrando ${name}, ${kind} en ${city}, ${county}.`,
    counties: { cache: 'Condado de Cache', saltlake: 'Condado de Salt Lake', utah: 'Condado de Utah' },
    kinds: {
      Diner: 'Cafetería', Taqueria: 'Taquería', Barbershop: 'Barbería', Bakery: 'Panadería',
      'Chicken shop': 'Pollería', Café: 'Café', Deli: 'Deli', Salon: 'Salón',
      Pizzeria: 'Pizzería', 'Nail salon': 'Salón de uñas',
    } as Record<string, string>,
  },
  packages: {
    title: 'Cuatro formas. El precio depende de dos cosas.',
    ledeBefore: 'Cuánto tablero ocupa tu anuncio, y ',
    ledeWhen: 'cuándo',
    ledeAfter: ' se muestra. Una franja debajo del menú es lo más barato que vendemos. Apagar todo el tablero es lo que más cuesta, porque mientras se muestra, el menú del negocio desaparece. La hora pico es el almuerzo y la cena, cuando hay fila; la tarde cuesta cerca de la mitad.',
    perMin: '/ min',
    slabFoot: (tier: string, minutes: string) => `${tier} · desde, para una franja inferior · ${minutes} min libres`,
    look: {
      banner: { sell: 'Una franja debajo del menú, a la vista todo el tiempo que alguien decide qué pedir.', note: 'Lo mínimo del tablero, así que lo mínimo a pagar.' },
      rail: { sell: 'El tercio derecho, de arriba abajo. Ocupa la pantalla de forma continua sin tapar nunca el menú.', note: 'Más tablero que una franja, y con precio acorde.' },
      full: { sell: 'Todo el tablero durante tu turno en la rotación. Nada más en él.', note: 'El menú desaparece mientras se muestra, que es justo lo que pagas.' },
      video: { sell: 'Quince segundos sin sonido en el espacio de pantalla completa. Movimiento en un local donde nada más se mueve.', note: 'Se cobra por reproducción, no por minuto. Compras un número de reproducciones.' },
    },
    peakPer: (unit: string) => `hora pico, por ${unit}`,
    offPeak: (rate: string) => `${rate} en hora baja`,
    payPlays: 'Pagas por las reproducciones que ocurrieron',
    payMinutes: 'Pagas por los minutos mostrados',
    buildOne: 'Crea una',
    foot: 'Cada precio de arriba es lo que pagas. No hay subasta, no compites contra una marca nacional por el negocio de tu esquina, y ninguna tarifa cambia según quién más apareció esa semana.',
  },
  reporting: {
    eyebrow: 'El panel real, no un dibujo',
    title: 'Sabe exactamente a dónde fue tu dinero.',
    ledeBefore: 'Cada pantalla de abajo es el creador y el reporte reales, capturados del producto. Puedes abrir el ',
    ledeLink: 'panel',
    ledeAfter: ' y crear una campaña ahora mismo, sin cuenta.',
    foot: 'AdBite cobra por dos cosas y reporta las dos: cuántas veces se reprodujo tu anuncio, y los minutos que estuvo en pantalla, separados en hora pico y hora baja, por negocio. Todo lo que se calcula en vez de contarse (personas que pasan frente al tablero, costo por mil) está marcado como tal en la pantalla donde aparece. Aquí no hay impresiones, ni estimaciones de alcance disfrazadas de mediciones.',
  },
  advertise: {
    eyebrow: 'Acceso al piloto',
    title: '¿Quieres anunciarte?',
    lede: 'Déjanos tus datos y te subimos al piloto. Una persona lo lee, encuentra los tableros que van con lo que vendes, y te responde con lo que está disponible y cuánto costaría.',
    form: {
      business: 'Tipo de negocio',
      businessPlaceholder: 'Florería, dentista, gimnasio…',
      where: 'Dónde estás',
      wherePlaceholder: 'Provo, Sandy, Logan…',
      budget: 'Presupuesto semanal',
      budgetPlaceholder: 'Elige un rango',
      message: 'Qué dirías',
      messagePlaceholder: 'Afinación gratis, dos cuadras al norte',
      email: 'Tu correo',
      emailPlaceholder: 'tu@tunegocio.com',
      submit: 'Súbeme al piloto',
      thanks: 'Gracias, te contactamos pronto',
      note: 'Te respondemos con los tableros que te convienen y cuánto cuesta una semana en ellos.',
    },
  },
  signin: {
    eyebrow: 'Creciendo en volumen',
    title: 'Apunta a tu ciudad. O solo a tu vecindario.',
    lede: 'Cada semana sumamos pantallas y traemos anunciantes. Dinos dónde estás y qué mostrarías, y te subimos a los tableros más cercanos a tus clientes.',
    points: [
      'Elige la ciudad, el vecindario y las horas. Tu anuncio se muestra en esos tableros y en ningún otro lado',
      'Sin subasta. La tarifa es la tarifa, y no cambia porque alguien con más presupuesto haya aparecido esa semana',
      'Pagas por lo que realmente se mostró, por minuto o por reproducción. Un anuncio que nunca se reprodujo nunca se cobra',
    ],
    ratherWrite: '¿Prefieres escribirnos?',
    panelTitle: 'Dinos dónde estás',
    runningAShop: '¿Tienes un negocio?',
    joinShop: 'Únete a la lista de espera',
    done: {
      title: 'Ya estás en la lista.',
      text: 'Buscamos el tablero más cercano a ti y te respondemos con lo que está disponible y cuánto costaría. Te responde una persona, no un mensaje automático.',
      build: 'Crea tu anuncio mientras esperas',
    },
    form: {
      name: 'Tu nombre',
      namePlaceholder: 'Sam Ortega',
      business: 'Negocio',
      businessPlaceholder: 'Iron Rose Gym',
      where: 'Dónde estás',
      wherePlaceholder: 'Provo, Sandy, Logan…',
      email: 'Correo',
      emailPlaceholder: 'tu@tunegocio.com',
      about: 'Qué te gustaría mostrar',
      aboutPlaceholder: 'Una franja para la hora del almuerzo, dos cuadras al norte',
      submit: 'Súbeme a un tablero',
      note: (mail: string) => `Llega directo a ${mail}, donde una persona lo lee. No se cobra nada y no te comprometes a nada.`,
    },
  },
};

export const ADVERTISERS = { en, es };
