/* The advertiser's landing page, and the invitation at /signin. */

const en = {
  nav: { buy: 'How it works', reporting: 'Reporting' },
  ads: [
    { label: 'Now playing · Bottom banner', brand: 'Iron Rose Gym', detail: 'First class free · two doors down' },
    { label: 'Now playing · Full screen', brand: 'Freedom Cycles', detail: 'Free tune-up · two blocks north' },
    { label: 'Now playing · Short video', brand: 'Ninth Street Books', detail: '10% off with your receipt' },
  ],
  hero: {
    title1: 'Show up where your neighbors ',
    title2: 'already look.',
    lede: 'Buy a slice of the menu board at a shop in your neighborhood. Your ad plays while someone is standing at the counter, already deciding what to spend money on.',
    build: 'Build your campaign',
    orContact: 'Or have us set it up',
  },
  boards: {
    title: 'See it running.',
    lede: 'A banner under a live menu, and a full-screen spot cutting into a shop’s own food. Your ad sits inside the one thing everyone in the room is already looking at, at the exact moment they are deciding what to spend money on.',
  },
  buy: {
    title: 'How it works. Two ways to buy.',
    lede: 'One is a place on a screen, held for a year. The other is time, bought by the hour and billed on what actually ran.',
    banner: {
      eyebrow: 'A place on a screen',
      name: 'Permanent spot',
      price: 'Contact us',
      per: 'for pricing',
      sell: 'A static ad in the strip under one shop’s menu. It is on that screen every hour the shop is open, for twelve months, and the menu above it stays readable the whole time. Each board holds a handful, so what it costs depends on which board, and which boards have one free changes week to week.',
      points: [
        'One shop, one screen, twelve months',
        'Shown at least 60 times an hour',
        'Still image, 1920 × 240 (1080 × 340 for a portrait screen)',
        'Invoiced once. Nothing to watch week to week',
      ],
      cta: 'Ask what is free near you',
    },
    video: {
      eyebrow: 'Time across the network',
      name: 'Short video',
      per: 'an hour shown',
      cta: 'Build one now',
      sell: 'Fifteen muted seconds between turns of the shop’s own footage. Buy an hour or a hundred, on one board or across the pilot, and you are billed on the time your spot was actually on screen.',
      points: [
        'Up to 0:15, muted, 1920 × 1080 (1080 × 1920 for a portrait screen)',
        'Billed on time actually shown',
        'Stop any week you like',
      ],
    },
    steps: [
      ['Pick your shops', 'One board near your door, a neighbourhood, or the whole pilot.'],
      ['Put your artwork up', 'Drop in the image or the clip. You see it on a real board before anyone else does.'],
      ['The shop says yes', 'Every creative waits for the owner’s approval. Nothing runs and nothing is billed until it has one.'],
      ['It runs, and you see it', 'Minutes and plays are counted by the player itself and reported back, per shop, every week.'],
    ] as [string, string][],
    foot: 'Both prices are what you pay. There is no auction, no bidding against a national brand for the shop on your corner, and no rate that moves because of who else showed up that week.',
    cta: 'Build your campaign',
  },
  reporting: {
    title: 'Know exactly where your money went.',
    ledeBefore: 'Every screen below is the real builder and the real report, captured from the product. You can open the ',
    ledeLink: 'dashboard',
    ledeAfter: ' and build a campaign right now. It takes an account, which is an email address and a link in the mail.',
  },
  advertise: {
    eyebrow: 'Pilot access',
    title: 'Want to advertise?',
    lede: 'Put your details in and we will get you onto the pilot. We find the boards that suit what you sell and write back with what is open and what it would cost.',
    form: {
      business: 'Business type',
      businessPlaceholder: 'Florist, dentist, gym…',
      where: 'Where you are',
      wherePlaceholder: 'Provo, Sandy, Logan…',
      budget: 'Weekly budget',
      budgetPlaceholder: 'Choose a range',
      message: 'What you would say',
      messagePlaceholder: 'Free tune-up, two blocks north',
      email: 'Your email',
      emailPlaceholder: 'you@yourbusiness.com',
      submit: 'Get me on the pilot',
      thanks: 'Thanks, we’ll be in touch',
      note: 'We’ll come back with the boards that suit you and what a week on them costs.',
    },
  },
  signin: {
    eyebrow: 'Ramping up volume',
    title: 'Target your city. Or just your neighborhood.',
    lede: 'We are adding screens and bringing advertisers on every week. Tell us where you are and what you would run, and we will get you onto the boards closest to your customers.',
    points: [
      'Pick the city, the neighborhood and the hours. Your ad runs on those boards and nowhere else',
      'No auction. The rate card is the rate, and it does not move because someone with a bigger budget turned up that week',
      'You pay for what actually ran, by the minute or by the play. An ad that never played is never billed',
    ],
    ratherWrite: 'Would rather just write?',
    panelTitle: 'Tell us where you are',
    runningAShop: 'Running a shop instead?',
    joinShop: 'Join the shop waitlist',
    done: {
      title: 'You’re on the list.',
      text: 'We will find the nearest board to you and come back with what is open on it and what it would cost. A person writes back, not an auto-responder.',
      build: 'Build your ad while you wait',
    },
    form: {
      name: 'Your name',
      namePlaceholder: 'Sam Ortega',
      business: 'Business',
      businessPlaceholder: 'Iron Rose Gym',
      where: 'Where you are',
      wherePlaceholder: 'Provo, Sandy, Logan…',
      email: 'Email',
      emailPlaceholder: 'you@yourbusiness.com',
      about: 'What you would want to run',
      aboutPlaceholder: 'A banner for the lunch rush, two blocks north',
      submit: 'Get me on a board',
      note: (mail: string) => `Goes straight to ${mail}. Nothing is charged and you are not committing to anything.`,
    },
  },
};

const es: typeof en = {
  nav: { buy: 'Cómo funciona', reporting: 'Reportes' },
  ads: [
    { label: 'En pantalla · Franja inferior', brand: 'Iron Rose Gym', detail: 'Primera clase gratis · dos puertas más allá' },
    { label: 'En pantalla · Pantalla completa', brand: 'Freedom Cycles', detail: 'Afinación gratis · dos cuadras al norte' },
    { label: 'En pantalla · Video corto', brand: 'Ninth Street Books', detail: '10% de descuento con tu recibo' },
  ],
  hero: {
    title1: 'Aparece donde tus vecinos ',
    title2: 'ya están mirando.',
    lede: 'Compra una parte del tablero de menú de un negocio de tu vecindario. Tu anuncio se muestra mientras alguien está parado en el mostrador, decidiendo en qué gastar.',
    build: 'Crea tu campaña',
    orContact: 'O deja que la armemos por ti',
  },
  boards: {
    title: 'Míralo funcionando.',
    lede: 'Una franja bajo un menú en vivo, y un anuncio a pantalla completa que corta la comida del propio negocio. Tu anuncio va dentro de lo único que todos en el local ya están mirando, justo cuando deciden en qué gastar.',
  },
  buy: {
    title: 'Cómo funciona. Dos formas de comprar.',
    lede: 'Una es un lugar en una pantalla, apartado por un año. La otra es tiempo, comprado por hora y cobrado por lo que realmente se mostró.',
    banner: {
      eyebrow: 'Un lugar en una pantalla',
      name: 'Espacio permanente',
      price: 'Habla con nosotros',
      per: 'para el precio',
      sell: 'Un anuncio fijo en la franja debajo del menú de un negocio. Está en esa pantalla cada hora que el negocio abre, durante doce meses, y el menú de arriba se sigue leyendo todo el tiempo. Cada tablero tiene unos pocos, así que el precio depende de cuál, y qué tableros tienen uno libre cambia cada semana.',
      points: [
        'Un negocio, una pantalla, doce meses',
        'Se muestra al menos 60 veces por hora',
        'Imagen fija, 1920 × 240 (1080 × 340 en pantalla vertical)',
        'Se factura una vez. Nada que vigilar cada semana',
      ],
      cta: 'Pregunta qué hay libre cerca de ti',
    },
    video: {
      eyebrow: 'Tiempo en toda la red',
      name: 'Video corto',
      per: 'por hora mostrada',
      cta: 'Crea uno ahora',
      sell: 'Quince segundos sin sonido entre turnos del propio video del negocio. Compra una hora o cien, en un tablero o en todo el piloto, y te cobramos por el tiempo que tu anuncio estuvo en pantalla.',
      points: [
        'Hasta 0:15, sin sonido, 1920 × 1080 (1080 × 1920 en pantalla vertical)',
        'Se cobra por el tiempo realmente mostrado',
        'Párala la semana que quieras',
      ],
    },
    steps: [
      ['Elige tus negocios', 'Un tablero cerca de tu puerta, un vecindario, o todo el piloto.'],
      ['Sube tu arte', 'Pon la imagen o el video. Lo ves en un tablero real antes que nadie.'],
      ['El negocio dice que sí', 'Cada anuncio espera la aprobación del dueño. Nada se muestra ni se cobra hasta tenerla.'],
      ['Se muestra, y lo ves', 'Los minutos y las reproducciones los cuenta el propio reproductor y se reportan por negocio, cada semana.'],
    ] as [string, string][],
    foot: 'Los dos precios son lo que pagas. No hay subasta, no compites contra una marca nacional por el negocio de tu esquina, y ninguna tarifa cambia según quién más apareció esa semana.',
    cta: 'Crea tu campaña',
  },
  reporting: {
    title: 'Sabe exactamente a dónde fue tu dinero.',
    ledeBefore: 'Cada pantalla de abajo es el creador y el reporte reales, capturados del producto. Puedes abrir el ',
    ledeLink: 'panel',
    ledeAfter: ' y crear una campaña ahora mismo. Necesitas una cuenta: tu correo y un enlace por mail.',
  },
  advertise: {
    eyebrow: 'Acceso al piloto',
    title: '¿Quieres anunciarte?',
    lede: 'Déjanos tus datos y te subimos al piloto. Encontramos los tableros que van con lo que vendes y te respondemos con lo que está disponible y cuánto costaría.',
    form: {
      business: 'Tipo de negocio',
      businessPlaceholder: 'Florería, dentista, gimnasio…',
      where: 'Dónde estás',
      wherePlaceholder: 'Provo, Sandy, Logan…',
      budget: 'Presupuesto semanal',
      budgetPlaceholder: 'Elige un rango',
      message: 'Qué dirías',
      messagePlaceholder: 'Afinación gratis, dos cuadras al norte',
      email: 'Tu correo',
      emailPlaceholder: 'tu@tunegocio.com',
      submit: 'Súbeme al piloto',
      thanks: 'Gracias, te contactamos pronto',
      note: 'Te respondemos con los tableros que te convienen y cuánto cuesta una semana en ellos.',
    },
  },
  signin: {
    eyebrow: 'Creciendo en volumen',
    title: 'Apunta a tu ciudad. O solo a tu vecindario.',
    lede: 'Cada semana sumamos pantallas y traemos anunciantes. Dinos dónde estás y qué mostrarías, y te subimos a los tableros más cercanos a tus clientes.',
    points: [
      'Elige la ciudad, el vecindario y las horas. Tu anuncio se muestra en esos tableros y en ningún otro lado',
      'Sin subasta. La tarifa es la tarifa, y no cambia porque alguien con más presupuesto haya aparecido esa semana',
      'Pagas por lo que realmente se mostró, por minuto o por reproducción. Un anuncio que nunca se reprodujo nunca se cobra',
    ],
    ratherWrite: '¿Prefieres escribirnos?',
    panelTitle: 'Dinos dónde estás',
    runningAShop: '¿Tienes un negocio?',
    joinShop: 'Únete a la lista de espera',
    done: {
      title: 'Ya estás en la lista.',
      text: 'Buscamos el tablero más cercano a ti y te respondemos con lo que está disponible y cuánto costaría. Te responde una persona, no un mensaje automático.',
      build: 'Crea tu anuncio mientras esperas',
    },
    form: {
      name: 'Tu nombre',
      namePlaceholder: 'Sam Ortega',
      business: 'Negocio',
      businessPlaceholder: 'Iron Rose Gym',
      where: 'Dónde estás',
      wherePlaceholder: 'Provo, Sandy, Logan…',
      email: 'Correo',
      emailPlaceholder: 'tu@tunegocio.com',
      about: 'Qué te gustaría mostrar',
      aboutPlaceholder: 'Una franja para la hora del almuerzo, dos cuadras al norte',
      submit: 'Súbeme a un tablero',
      note: (mail: string) => `Llega directo a ${mail}. No se cobra nada y no te comprometes a nada.`,
    },
  },
};

export const ADVERTISERS = { en, es };
