/* The advertiser's workspace: the dashboard, the three-step builder, the
 * reporting panel, and the two marketing widgets that show them off. */

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

const en = {
  dash: {
    steps: [
      { title: 'Place it', note: 'Shops, groups and map' },
      { title: 'Buy it', note: 'A spot, or video by the hour' },
      { title: 'Make it', note: 'Artwork and previews' },
    ],
    back: 'Dashboard',
    newCampaign: 'New campaign',
    send: {
      title: 'Send it to us',
      hint: 'A person picks this up, not a queue.',
      email: 'Your email',
      emailPlaceholder: 'you@yourshop.com',
      note: 'AdBite is in pilot, so this goes to info@adbite.site as a request rather than booking the week outright. Nothing is charged now, the shop owner reviews your creative before anything runs, and you only ever pay for what actually plays.',
      couldNotSave: 'Could not save the campaign',
    },
    bar: {
      perWeek: (unit: string) => `${unit} / week`,
      spend: 'A week',
      spots: 'Spots',
      hours: 'On screen',
      onceOff: 'Invoiced once',
      perSpot: (n: string) => `${n} a year, per screen`,
      perHour: (n: string) => `${n} an hour shown`,
      noSpots: 'No spots free on the shops you picked.',
      shops: 'Shops',
      format: 'Format',
      rate: 'Rate',
      pickOne: 'Pick at least one shop.',
      upload: 'Upload your artwork to submit.',
      addEmail: 'Add an email so we can reply.',
      back: 'Back',
      cancel: 'Cancel',
      submit: 'Send this to AdBite',
      next: 'Continue',
    },
    status: { onScreen: 'On screen', inReview: 'In review with the shop', sample: 'Sample' },
    detail: {
      booked: (date: string) => `Booked ${date}`,
      playingSince: (date: string) => ` · playing since ${date}`,
      delete: 'Delete',
      banner: 'Nothing has played yet, so every figure below is the week you booked rather than a week that ran. Reporting switches over the first time the board plays your spot.',
    },
    head: {
      advertiser: 'Advertiser',
      title: 'Your campaigns',
      onScreen: 'On screen',
      weeklySpend: 'Weekly spend',
      spentToDate: 'Spent to date',
      minutesPerWeek: 'Minutes / week',
      screensReachable: 'Screens reachable',
    },
    list: {
      label: 'Your campaigns',
      meta: (shops: number, minutes: string, spent: string | null) =>
        `${shops} ${plural(shops, 'shop', 'shops')} · ${minutes} min / wk${spent ? ` · ${spent} spent` : ''}`,
      removeSamples: 'Remove the samples',
    },
    empty: {
      title: 'No campaigns yet.',
      text: (live: number, minutes: string, coming: number) =>
        `AdBite is going in across Salt Lake, Utah and Cache counties. ${live} ${plural(live, 'board is', 'boards are')} playing ads today, holding ${minutes} minutes of ad time a week, and another ${coming} shops are being installed and can be booked ahead.`,
      samples: 'Load four worked examples',
      note: 'Made-up bookings: three with a few weeks on the clock so the reporting has something to show, and one still waiting on the shop owner. They are badged Sample everywhere and clear in one click.',
    },
  },
  place: {
    detail: {
      close: 'Close',
      monthlyTraffic: 'Monthly traffic',
      monthlyNote: 'Heads past the board, counted over a month',
      spotsFree: 'Spots free',
      spotsNote: (total: number) => `of ${total} on this board`,
      screens: 'Screens',
      videoHours: 'Video hours a week',
      videoNote: 'What this board can carry on top of its spots',
      open: 'Open',
      add: 'Add to this campaign',
      remove: 'Remove from this campaign',
      onIt: 'On this campaign',
      fullBoard: 'Every spot on this board is taken. You can still run video here.',
      prospect: 'Not live yet. Adding it puts it on the request rather than on a bill.',
    },
    tools: {
      pan: { label: 'Pick', hint: 'Click a pin to add or drop that shop' },
      radius: { label: 'Radius', hint: 'Press on the map and drag out from your own door' },
      lasso: { label: 'Draw area', hint: 'Click corners around a block. Double-click to close it' },
    },
    search: 'Search shops, streets, cuisines',
    searchLabel: 'Search the network',
    clearSearch: 'Clear search',
    neighbourhoods: 'Neighbourhoods',
    kinds: 'Kinds of shop',
    chipTitle: (blurb: string, n: number) => `${blurb}. Click to take all ${n}; shift-click to filter the list.`,
    shown: (visible: number, total: number) =>
      visible === total ? `${total} shops` : `${visible} of ${total} shown`,
    selectShown: 'Select shown',
    clear: 'Clear',
    resetFilters: 'Reset filters',
    nothingMatches: 'Nothing matches that.',
    whoTitle: 'Who you hope to reach',
    whoNote: 'A request on the booking, not a targeting guarantee: one rotation, whole room.',
    mapTools: 'Map selection tools',
    undo: 'Undo',
    drawn: (shape: string, n: number) => `${shape} · ${n} ${plural(n, 'shop', 'shops')} added`,
    radiusShape: (label: string) => `${label} radius`,
    areaShape: (points: number) => `hand-drawn area, ${points} points`,
    foot: { shops: 'Shops', of: (n: number) => ` of ${n}`, screens: 'Screens', spots: 'Spots free', heads: 'Heads past the board' },
    note: (live: number, chosen: number) =>
      `${live} of the ${chosen} ${plural(chosen, 'shop', 'shops')} you have picked ${plural(live, 'is', 'are')} playing ads today. The rest are boards we are installing: they travel with your request and hold your slot, and nothing is billed for one until its screen is up.`,
  },
  buy: {
    title: 'What are you buying?',
    hint: 'Two things, bought in different shapes.',
    spot: {
      name: 'A permanent spot',
      note: 'A static ad in the strip under the menu, on one screen, for twelve months.',
      unit: 'a year, per screen',
      pick: 'How many boards',
      picked: (n: number, free: number) => `${n} of ${free} free on the shops you picked`,
      none: 'None of the shops you picked have a spot free. Take some others in step 01, or write to us and we will tell you what is coming up.',
      total: 'Invoiced once',
      per: 'for twelve months',
      foot: 'Nothing is metered and nothing runs on a clock. You are invoiced once the shop approves the artwork, and the spot is yours for the year.',
    },
    video: {
      name: 'Short video',
      note: 'Fifteen muted seconds between turns of the shop’s own footage.',
      unit: 'an hour shown',
      pick: 'Hours a week',
      picked: (hours: string, cap: string) => `${hours} of the ${cap} these boards can carry`,
      total: 'Invoiced weekly',
      per: 'on the hours that actually ran',
      foot: 'One flat rate at every hour of the day. An hour that did not run is never invoiced, and anything booked that did not run rolls into the next week.',
    },
    whenTitle: 'When it runs',
    whenHint: 'Every hour costs the same. Pick any mix.',
    whenAll: 'A permanent spot is up whenever the shop is open, so there are no hours to pick.',
    weekdays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    shut: 'shut',
    minutesAWeek: 'Minutes on screen, each week',
    perDay: 'minutes a day, across the week',
    screensHeld: (screens: number, shops: number) =>
      `${screens} ${plural(screens, 'screen', 'screens')} across ${shops} ${plural(shops, 'shop', 'shops')}`,
    full: 'That is every minute these boards have in this mix. There is nothing more to sell until another screen joins.',
  },
  creative: {
    notImage: 'That file isn’t artwork we can play. Upload a PNG or JPG, or an MP4 for a video spot.',
    tooBig: 'That file is too big. Images go up to 6 MB, video up to 12 MB.',
    tooLong: 'A video spot runs 20 seconds or less. Trim it and try again.',
    uploading: 'Sending to the boards…',
    uploadFailed: 'That upload did not finish.',
    changeBack: ' Change what you are buying, or how much of it, back in step 02.',
    upload: 'Upload your ad',
    uploadedAlt: 'Your uploaded ad creative',
    placed: 'Placed in every preview below.',
    replace: 'Replace',
    remove: 'Remove',
    drop: 'Drop your artwork here',
    dropSub: 'or choose a file · PNG, JPG or MP4',
    previews: 'On the screens we run',
    previewsHint: (n: number, total: number) => `${n} of ${total} board types carry this format.`,
    yourAdHere: 'Your ad here',
    noFormat: 'Doesn’t carry this format',
    boardAlt: (name: string) => `${name} board`,
  },
  analytics: {
    tabs: { overview: 'Overview', where: 'Where it ran', when: 'When it ran', creative: 'Creative' },
    tabsLabel: 'Campaign reporting',
    spendToDate: 'Spend to date',
    bookedForWeek: 'Booked for the week',
    daysAt: (days: number, weekly: string) => `${days} ${plural(days, 'day', 'days')} · ${weekly} / wk`,
    nothingCharged: 'Nothing is charged until it plays',
    playsDelivered: 'Plays delivered',
    minutesOnScreen: 'Minutes on screen',
    ofScreenTime: (hours: string) => `${hours} of screen time`,
    playsOf15: (n: string) => `${n} plays of 0:15`,
    costPer: (unit: string) => `Cost per ${unit}`,
    aMinuteAPlay: (min: string, play: string) => `${min} a minute · ${play} a play`,
    heads: 'Heads past the board',
    perThousand: (n: string) => `${n} per thousand`,
    shops: 'Shops',
    screensAreas: (screens: number, areas: number) =>
      `${screens} ${plural(screens, 'screen', 'screens')} · ${areas} ${plural(areas, 'area', 'areas')}`,
    format: 'Format',
    billedBy: (unit: string) => `Billed by the ${unit}`,
    billedOnce: 'Invoiced once, for the year',
    dayByDay: 'Day by day',
    weekAsBooked: 'The week as booked',
    busiest: (days: number, weekday: string, spend: string) => `${days} days · busiest was ${weekday} at ${spend}`,
    startsWhen: 'Starts the day the shop approves your creative',
    dailyCaption: (days: number) => `Daily spend across ${days} days, one bar a day.`,
    nothingPlayed: 'Nothing has played yet. This chart fills in from the first day the board runs your spot, one bar a day.',
    weeklyBudget: 'Weekly budget',
    perWeek: (unit: string) => `${unit} a week`,
    weeksRun: 'Weeks run',
    bestShop: 'Best shop',
    howTitle: 'How this is worked out',
    how1: (rate: string) => `Your week is spread across the shops you booked in proportion to what each one has to sell, then priced at the flat video rate you saw when you booked: ${rate} a minute, at every hour of the day. A permanent spot never appears here: it is bought outright for the year rather than metered.`,
    how2: 'Heads past the board is a planning figure from each shop’s own footfall, pro-rated by the share of its open week your ad occupied. It is not a count of faces and nothing here measures attention.',
    everyScreen: 'Every screen it played on',
    shopsScreens: (shops: number, screens: number) =>
      `${shops} ${plural(shops, 'shop', 'shops')} · ${screens} ${plural(screens, 'screen', 'screens')}`,
    th: { shop: 'Shop', area: 'Area', screens: 'Screens', time: 'Time on screen', heads: 'Heads', rate: 'Rate', spend: 'Spend', share: 'Share of spend' },
    installing: 'Installing',
    onTheMap: 'On the map',
    reachPerDollar: 'Reach per dollar',
    headsPerDollar: 'heads / $',
    trimNote: 'Cheap minutes in a busy room go furthest. This is the order to trim from if the budget has to come down.',
    hourByHour: 'Hour by hour',
    hourSub: 'Minutes of screen time, across the shop day',
    hourCaption: 'Minutes of screen time by hour of the shop day.',
    hourTitle: (label: string, minutes: string) => `${label} · ${minutes} minutes`,
    hourNote: 'Every daypart you bought lands evenly across the hours it covers. Nothing here counts footfall by the hour, and a curve drawn from nothing would be a lie told in a prettier shape.',
    daypartCost: 'What each daypart cost',
    daypartSub: (bought: number, rate: string) => `${bought} of 3 bought · ${rate} a minute blended`,
    perMin: '/ min',
    costInShape: 'What it costs in this shape',
    rateOnMix: 'Rate on this mix',
    costOnePlay: 'Cost of one play',
    costHour: 'Cost of an hour on screen',
    monthAtPace: 'A month at this pace',
    shapeNote: ' Change the shape and the price moves with it: a strip under the menu is the least we ask the room for and the least we charge.',
    artwork: 'Artwork',
    onFile: 'Artwork on file',
    exampleNote: ' · shown on an example board to illustrate the slot. The boards you booked are not pictured.',
    boardAlt: (name: string) => `${name} board`,
    days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  tour: {
    label: 'Dashboard tour',
    pause: 'Pause the tour',
    play: 'Play the tour',
    open: 'Open it yourself',
    frames: [
      { tab: 'Pick the shops', title: 'Pick the shops, or draw the block.', note: 'Search the network, take a whole neighbourhood in one press, or circle a radius around your own front door and take everything inside it.' },
      { tab: 'Drop the artwork', title: 'Your artwork, in the slot it will occupy.', note: 'Drop in a PNG and it appears on every board type that carries your format, at the size and position it will actually run.' },
      { tab: 'Watch it run', title: 'Then watch what it does.', note: 'Spend to date, minutes on screen, cost per play and cost per thousand heads, with a bar for every day since the board started playing it.' },
      { tab: 'Where it ran', title: 'Down to the screen.', note: 'Every shop it played on, how long it held each one, what that shop cost and what share of the week it took.' },
      { tab: 'When it ran', title: 'And down to the hour.', note: 'Which hours you bought and where the minutes actually landed across the shop day. One flat rate, so this is a picture of delivery rather than of pricing.' },
    ],
  },
};

const es: typeof en = {
  dash: {
    steps: [
      { title: 'Ubícalo', note: 'Negocios, grupos y mapa' },
      { title: 'Cómpralo', note: 'Un espacio, o video por hora' },
      { title: 'Créalo', note: 'Arte y vistas previas' },
    ],
    back: 'Panel',
    newCampaign: 'Nueva campaña',
    send: {
      title: 'Envíanoslo',
      hint: 'Lo recibe una persona, no una cola.',
      email: 'Tu correo',
      emailPlaceholder: 'tu@tunegocio.com',
      note: 'AdBite está en piloto, así que esto llega a info@adbite.site como solicitud, no como una reserva definitiva de la semana. No se cobra nada ahora, el dueño del negocio revisa tu anuncio antes de que se muestre, y solo pagas por lo que realmente se reproduce.',
      couldNotSave: 'No se pudo guardar la campaña',
    },
    bar: {
      perWeek: (unit: string) => `${unit} / semana`,
      spend: 'A la semana',
      spots: 'Espacios',
      hours: 'En pantalla',
      onceOff: 'Se factura una vez',
      perSpot: (n: string) => `${n} al año, por pantalla`,
      perHour: (n: string) => `${n} por hora mostrada`,
      noSpots: 'No hay espacios libres en los negocios que elegiste.',
      shops: 'Negocios',
      format: 'Formato',
      rate: 'Tarifa',
      pickOne: 'Elige al menos un negocio.',
      upload: 'Sube tu arte para enviar.',
      addEmail: 'Agrega un correo para poder responderte.',
      back: 'Atrás',
      cancel: 'Cancelar',
      submit: 'Enviar a AdBite',
      next: 'Continuar',
    },
    status: { onScreen: 'En pantalla', inReview: 'En revisión con el negocio', sample: 'Ejemplo' },
    detail: {
      booked: (date: string) => `Reservado el ${date}`,
      playingSince: (date: string) => ` · en pantalla desde el ${date}`,
      delete: 'Eliminar',
      banner: 'Todavía no se ha reproducido nada, así que cada cifra de abajo es la semana que reservaste, no una semana que ocurrió. Los reportes cambian la primera vez que el tablero reproduce tu anuncio.',
    },
    head: {
      advertiser: 'Anunciante',
      title: 'Tus campañas',
      onScreen: 'En pantalla',
      weeklySpend: 'Gasto semanal',
      spentToDate: 'Gastado hasta hoy',
      minutesPerWeek: 'Minutos / semana',
      screensReachable: 'Pantallas disponibles',
    },
    list: {
      label: 'Tus campañas',
      meta: (shops: number, minutes: string, spent: string | null) =>
        `${shops} ${plural(shops, 'negocio', 'negocios')} · ${minutes} min / sem${spent ? ` · ${spent} gastados` : ''}`,
      removeSamples: 'Quitar los ejemplos',
    },
    empty: {
      title: 'Todavía no hay campañas.',
      text: (live: number, minutes: string, coming: number) =>
        `AdBite se está instalando en los condados de Salt Lake, Utah y Cache. Hoy ${live} ${plural(live, 'tablero está mostrando', 'tableros están mostrando')} anuncios, con ${minutes} minutos de tiempo de anuncios a la semana, y otros ${coming} negocios están en instalación y se pueden reservar por adelantado.`,
      samples: 'Cargar cuatro ejemplos',
      note: 'Reservas inventadas: tres con algunas semanas corridas para que los reportes tengan algo que mostrar, y una todavía esperando al dueño del negocio. Llevan la etiqueta Ejemplo en todos lados y se borran con un clic.',
    },
  },
  place: {
    detail: {
      close: 'Cerrar',
      monthlyTraffic: 'Tráfico mensual',
      monthlyNote: 'Personas que pasan frente al tablero, en un mes',
      spotsFree: 'Espacios libres',
      spotsNote: (total: number) => `de ${total} en este tablero`,
      screens: 'Pantallas',
      videoHours: 'Horas de video por semana',
      videoNote: 'Lo que este tablero puede llevar además de sus espacios',
      open: 'Horario',
      add: 'Agregar a esta campaña',
      remove: 'Quitar de esta campaña',
      onIt: 'En esta campaña',
      fullBoard: 'Todos los espacios de este tablero están tomados. Todavía puedes poner video aquí.',
      prospect: 'Todavía no está activo. Agregarlo lo pone en la solicitud, no en una factura.',
    },
    tools: {
      pan: { label: 'Elegir', hint: 'Haz clic en un pin para agregar o quitar ese negocio' },
      radius: { label: 'Radio', hint: 'Presiona en el mapa y arrastra desde tu propia puerta' },
      lasso: { label: 'Dibujar zona', hint: 'Haz clic en las esquinas de una cuadra. Doble clic para cerrar' },
    },
    search: 'Busca negocios, calles, tipos de comida',
    searchLabel: 'Buscar en la red',
    clearSearch: 'Borrar búsqueda',
    neighbourhoods: 'Vecindarios',
    kinds: 'Tipos de negocio',
    chipTitle: (blurb: string, n: number) => `${blurb}. Clic para tomar los ${n}; shift + clic para filtrar la lista.`,
    shown: (visible: number, total: number) =>
      visible === total ? `${total} negocios` : `${visible} de ${total} mostrados`,
    selectShown: 'Seleccionar los mostrados',
    clear: 'Limpiar',
    resetFilters: 'Quitar filtros',
    nothingMatches: 'Nada coincide con eso.',
    whoTitle: 'A quién esperas llegar',
    whoNote: 'Una solicitud en la reserva, no una garantía de segmentación: una rotación, todo el local.',
    mapTools: 'Herramientas de selección en el mapa',
    undo: 'Deshacer',
    drawn: (shape: string, n: number) => `${shape} · ${n} ${plural(n, 'negocio agregado', 'negocios agregados')}`,
    radiusShape: (label: string) => `Radio de ${label}`,
    areaShape: (points: number) => `zona dibujada a mano, ${points} puntos`,
    foot: { shops: 'Negocios', of: (n: number) => ` de ${n}`, screens: 'Pantallas', spots: 'Espacios libres', heads: 'Personas frente al tablero' },
    note: (live: number, chosen: number) =>
      `${live} de los ${chosen} ${plural(chosen, 'negocio', 'negocios')} que elegiste ${plural(live, 'está mostrando', 'están mostrando')} anuncios hoy. El resto son tableros que estamos instalando: viajan con tu solicitud y guardan tu lugar, y no se cobra nada por uno hasta que su pantalla esté encendida.`,
  },
  buy: {
    title: '¿Qué estás comprando?',
    hint: 'Dos cosas, que se compran de formas distintas.',
    spot: {
      name: 'Un espacio permanente',
      note: 'Un anuncio fijo en la franja debajo del menú, en una pantalla, por doce meses.',
      unit: 'al año, por pantalla',
      pick: 'Cuántos tableros',
      picked: (n: number, free: number) => `${n} de ${free} libres en los negocios que elegiste`,
      none: 'Ninguno de los negocios que elegiste tiene un espacio libre. Toma otros en el paso 01, o escríbenos y te decimos qué se va a liberar.',
      total: 'Se factura una vez',
      per: 'por doce meses',
      foot: 'Nada se mide y nada corre contra un reloj. Se te factura cuando el negocio aprueba el arte, y el espacio es tuyo por el año.',
    },
    video: {
      name: 'Video corto',
      note: 'Quince segundos sin sonido entre turnos del propio video del negocio.',
      unit: 'por hora mostrada',
      pick: 'Horas por semana',
      picked: (hours: string, cap: string) => `${hours} de las ${cap} que estos tableros pueden llevar`,
      total: 'Se factura cada semana',
      per: 'por las horas que realmente se mostraron',
      foot: 'Una tarifa plana a cualquier hora del día. Una hora que no se mostró nunca se factura, y lo reservado que no corrió pasa a la siguiente semana.',
    },
    whenTitle: 'Cuándo se muestra',
    whenHint: 'Todas las horas cuestan igual. Elige cualquier combinación.',
    whenAll: 'Un espacio permanente está puesto siempre que el negocio abre, así que no hay horas que elegir.',
    weekdays: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
    shut: 'cerrado',
    minutesAWeek: 'Minutos en pantalla, cada semana',
    perDay: 'minutos por día, a lo largo de la semana',
    screensHeld: (screens: number, shops: number) =>
      `${screens} ${plural(screens, 'pantalla', 'pantallas')} en ${shops} ${plural(shops, 'negocio', 'negocios')}`,
    full: 'Eso es cada minuto que estos tableros tienen en esta mezcla. No hay más que vender hasta que se sume otra pantalla.',
  },
  creative: {
    notImage: 'Ese archivo no es arte que podamos reproducir. Sube un PNG o JPG, o un MP4 para un anuncio en video.',
    tooBig: 'Ese archivo pesa demasiado. Las imágenes llegan a 6 MB y el video a 12 MB.',
    tooLong: 'Un anuncio en video dura 20 segundos o menos. Recórtalo e inténtalo de nuevo.',
    uploading: 'Enviando a los tableros…',
    uploadFailed: 'Esa subida no se completó.',
    changeBack: ' Cambia qué estás comprando, o cuánto, en el paso 02.',
    upload: 'Sube tu anuncio',
    uploadedAlt: 'El anuncio que subiste',
    placed: 'Colocado en todas las vistas previas de abajo.',
    replace: 'Reemplazar',
    remove: 'Quitar',
    drop: 'Arrastra tu arte aquí',
    dropSub: 'o elige un archivo · PNG, JPG o MP4',
    previews: 'En las pantallas que operamos',
    previewsHint: (n: number, total: number) => `${n} de ${total} tipos de tablero aceptan este formato.`,
    yourAdHere: 'Tu anuncio aquí',
    noFormat: 'No acepta este formato',
    boardAlt: (name: string) => `Tablero de ${name}`,
  },
  analytics: {
    tabs: { overview: 'Resumen', where: 'Dónde se mostró', when: 'Cuándo se mostró', creative: 'Anuncio' },
    tabsLabel: 'Reportes de la campaña',
    spendToDate: 'Gastado hasta hoy',
    bookedForWeek: 'Reservado para la semana',
    daysAt: (days: number, weekly: string) => `${days} ${plural(days, 'día', 'días')} · ${weekly} / sem`,
    nothingCharged: 'No se cobra nada hasta que se reproduce',
    playsDelivered: 'Reproducciones entregadas',
    minutesOnScreen: 'Minutos en pantalla',
    ofScreenTime: (hours: string) => `${hours} de tiempo en pantalla`,
    playsOf15: (n: string) => `${n} reproducciones de 0:15`,
    costPer: (unit: string) => `Costo por ${unit}`,
    aMinuteAPlay: (min: string, play: string) => `${min} por minuto · ${play} por reproducción`,
    heads: 'Personas frente al tablero',
    perThousand: (n: string) => `${n} por mil`,
    shops: 'Negocios',
    screensAreas: (screens: number, areas: number) =>
      `${screens} ${plural(screens, 'pantalla', 'pantallas')} · ${areas} ${plural(areas, 'zona', 'zonas')}`,
    format: 'Formato',
    billedBy: (unit: string) => `Se cobra por ${unit}`,
    billedOnce: 'Se factura una vez, por el año',
    dayByDay: 'Día por día',
    weekAsBooked: 'La semana como se reservó',
    busiest: (days: number, weekday: string, spend: string) => `${days} días · el más activo fue ${weekday} con ${spend}`,
    startsWhen: 'Empieza el día que el negocio aprueba tu anuncio',
    dailyCaption: (days: number) => `Gasto diario en ${days} días, una barra por día.`,
    nothingPlayed: 'Todavía no se ha reproducido nada. Esta gráfica se llena desde el primer día que el tablero muestra tu anuncio, una barra por día.',
    weeklyBudget: 'Presupuesto semanal',
    perWeek: (unit: string) => `${unit} por semana`,
    weeksRun: 'Semanas corridas',
    bestShop: 'Mejor negocio',
    howTitle: 'Cómo se calcula esto',
    how1: (rate: string) => `Tu semana se reparte entre los negocios que reservaste en proporción a lo que cada uno tiene para vender, y se cobra con la tarifa plana de video que viste al reservar: ${rate} por minuto, a cualquier hora del día. Un espacio permanente nunca aparece aquí: se compra por el año, no se mide.`,
    how2: 'Las personas frente al tablero son una cifra de planeación tomada del flujo de cada negocio, prorrateada por la parte de su semana abierta que ocupó tu anuncio. No es un conteo de caras y nada aquí mide atención.',
    everyScreen: 'Cada pantalla donde se mostró',
    shopsScreens: (shops: number, screens: number) =>
      `${shops} ${plural(shops, 'negocio', 'negocios')} · ${screens} ${plural(screens, 'pantalla', 'pantallas')}`,
    th: { shop: 'Negocio', area: 'Zona', screens: 'Pantallas', time: 'Tiempo en pantalla', heads: 'Personas', rate: 'Tarifa', spend: 'Gasto', share: 'Parte del gasto' },
    installing: 'En instalación',
    onTheMap: 'En el mapa',
    reachPerDollar: 'Alcance por dólar',
    headsPerDollar: 'personas / $',
    trimNote: 'Los minutos baratos en un local concurrido rinden más. Este es el orden para recortar si el presupuesto tiene que bajar.',
    hourByHour: 'Hora por hora',
    hourSub: 'Minutos de tiempo en pantalla, a lo largo del día del negocio',
    hourCaption: 'Minutos de tiempo en pantalla por hora del día del negocio.',
    hourTitle: (label: string, minutes: string) => `${label} · ${minutes} minutos`,
    hourNote: 'Cada franja horaria que compraste se reparte de forma pareja en las horas que cubre. Nada aquí cuenta el flujo por hora, y una curva dibujada de la nada sería una mentira con mejor forma.',
    daypartCost: 'Cuánto costó cada franja',
    daypartSub: (bought: number, rate: string) => `${bought} de 3 compradas · ${rate} por minuto en promedio`,
    perMin: '/ min',
    costInShape: 'Cuánto cuesta en esta forma',
    rateOnMix: 'Tarifa en esta mezcla',
    costOnePlay: 'Costo de una reproducción',
    costHour: 'Costo de una hora en pantalla',
    monthAtPace: 'Un mes a este ritmo',
    shapeNote: ' Cambia la forma y el precio cambia con ella: una franja debajo del menú es lo mínimo que le pedimos al local y lo mínimo que cobramos.',
    artwork: 'Arte',
    onFile: 'Arte en archivo',
    exampleNote: ' · mostrado en un tablero de ejemplo para ilustrar el espacio. Los tableros que reservaste no aparecen en la imagen.',
    boardAlt: (name: string) => `Tablero de ${name}`,
    days: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  },
  tour: {
    label: 'Recorrido por el panel',
    pause: 'Pausar el recorrido',
    play: 'Reproducir el recorrido',
    open: 'Ábrelo tú mismo',
    frames: [
      { tab: 'Elige los negocios', title: 'Elige los negocios, o dibuja la cuadra.', note: 'Busca en la red, toma un vecindario entero con un clic, o traza un radio alrededor de tu propia puerta y toma todo lo que quede dentro.' },
      { tab: 'Sube el arte', title: 'Tu arte, en el espacio que va a ocupar.', note: 'Sube un PNG y aparece en cada tipo de tablero que acepta tu formato, con el tamaño y la posición reales.' },
      { tab: 'Míralo correr', title: 'Después mira qué hace.', note: 'Gasto hasta hoy, minutos en pantalla, costo por reproducción y costo por mil personas, con una barra por cada día desde que el tablero empezó a mostrarlo.' },
      { tab: 'Dónde se mostró', title: 'Hasta la pantalla.', note: 'Cada negocio donde se mostró, cuánto tiempo estuvo en cada uno, cuánto costó ese negocio y qué parte de la semana ocupó.' },
      { tab: 'Cuándo se mostró', title: 'Y hasta la hora.', note: 'Qué horas compraste y dónde cayeron realmente los minutos a lo largo del día del negocio. Una tarifa plana, así que esto es una imagen de la entrega y no del precio.' },
    ],
  },
};

export const CAMPAIGN = { en, es };
