/* The advertiser's workspace: the dashboard, the three-step builder, the
 * reporting panel, and the two marketing widgets that show them off. */

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

const en = {
  dash: {
    steps: [
      { title: 'Place it', note: 'Shops, groups and map' },
      { title: 'Price it', note: 'Shape, timing and spend' },
      { title: 'Make it', note: 'Artwork and previews' },
    ],
    back: 'Dashboard',
    newCampaign: 'New campaign',
    send: {
      title: 'Send it to us',
      hint: 'A person picks this up, not a queue.',
      email: 'Your email',
      emailPlaceholder: 'you@yourshop.com',
      note: 'AdBite is in pilot, so this goes to info@adbite.site as a request rather than booking the week outright. Nothing is charged now, the shop owner reviews your creative before anything runs, and you only ever pay for what actually plays.',
      couldNotSave: 'Could not save the campaign',
    },
    bar: {
      perWeek: (unit: string) => `${unit} / week`,
      spend: 'Spend',
      shops: 'Shops',
      format: 'Format',
      rate: 'Rate',
      rateLine: (peak: string, off: string) => `${peak} peak · ${off} off`,
      pickOne: 'Pick at least one shop.',
      upload: 'Upload your artwork to submit.',
      addEmail: 'Add an email so we can reply.',
      back: 'Back',
      cancel: 'Cancel',
      submit: 'Send this to AdBite',
      next: 'Continue',
    },
    status: { onScreen: 'On screen', inReview: 'In review with the shop', sample: 'Sample' },
    detail: {
      booked: (date: string) => `Booked ${date}`,
      playingSince: (date: string) => ` · playing since ${date}`,
      delete: 'Delete',
      banner: 'Nothing has played yet, so every figure below is the week you booked rather than a week that ran. Reporting switches over the first time the board plays your spot.',
    },
    head: {
      advertiser: 'Advertiser',
      title: 'Your campaigns',
      onScreen: 'On screen',
      weeklySpend: 'Weekly spend',
      spentToDate: 'Spent to date',
      minutesPerWeek: 'Minutes / week',
      screensReachable: 'Screens reachable',
    },
    list: {
      label: 'Your campaigns',
      meta: (shops: number, minutes: string, spent: string | null) =>
        `${shops} ${plural(shops, 'shop', 'shops')} · ${minutes} min / wk${spent ? ` · ${spent} spent` : ''}`,
      removeSamples: 'Remove the samples',
    },
    empty: {
      title: 'No campaigns yet.',
      text: (live: number, minutes: string, coming: number) =>
        `AdBite is going in across Salt Lake, Utah and Cache counties. ${live} ${plural(live, 'board is', 'boards are')} playing ads today, holding ${minutes} minutes of ad time a week, and another ${coming} shops are being installed and can be booked ahead.`,
      samples: 'Load four worked examples',
      note: 'Made-up bookings: three with a few weeks on the clock so the reporting has something to show, and one still waiting on the shop owner. They are badged Sample everywhere and clear in one click.',
    },
  },
  place: {
    tools: {
      pan: { label: 'Pick', hint: 'Click a pin to add or drop that shop' },
      radius: { label: 'Radius', hint: 'Press on the map and drag out from your own door' },
      lasso: { label: 'Draw area', hint: 'Click corners around a block. Double-click to close it' },
    },
    search: 'Search shops, streets, cuisines',
    searchLabel: 'Search the network',
    clearSearch: 'Clear search',
    neighbourhoods: 'Neighbourhoods',
    kinds: 'Kinds of shop',
    chipTitle: (blurb: string, n: number) => `${blurb}. Click to take all ${n}; shift-click to filter the list.`,
    shown: (visible: number, total: number) =>
      visible === total ? `${total} shops` : `${visible} of ${total} shown`,
    selectShown: 'Select shown',
    clear: 'Clear',
    resetFilters: 'Reset filters',
    nothingMatches: 'Nothing matches that.',
    whoTitle: 'Who you hope to reach',
    whoNote: 'A request on the booking, not a targeting guarantee: one rotation, whole room.',
    mapTools: 'Map selection tools',
    undo: 'Undo',
    drawn: (shape: string, n: number) => `${shape} · ${n} ${plural(n, 'shop', 'shops')} added`,
    radiusShape: (label: string) => `${label} radius`,
    areaShape: (points: number) => `hand-drawn area, ${points} points`,
    foot: { shops: 'Shops', of: (n: number) => ` of ${n}`, screens: 'Screens', minutes: 'Minutes a week', heads: 'Heads past the board' },
    note: (live: number, chosen: number) =>
      `${live} of the ${chosen} ${plural(chosen, 'shop', 'shops')} you have picked ${plural(live, 'is', 'are')} playing ads today. The rest are boards we are installing: they travel with your request and hold your slot, and nothing is billed for one until its screen is up.`,
  },
  spend: {
    presets: [
      { label: 'Afternoons', note: 'Cheapest minutes' },
      { label: 'Lunch rush', note: 'Peak, 11am-2pm' },
      { label: 'Dinner rush', note: 'Peak, 5pm-9pm' },
      { label: 'Every open hour', note: 'The whole week' },
    ],
    weekdays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    eyebrowPlays: 'Times your ad plays, each week',
    eyebrowMinutes: 'Minutes your ad is on screen, each week',
    min: 'min',
    perWeekOnMix: (rate: string, unit: string) => `per week · ${rate} a ${unit} on this mix`,
    perDay: (unit: string) => `${unit} a day, across the week`,
    shut: 'shut',
    playsOf: 'plays of a 0:15 spot',
    screenTime: 'of screen time a week',
    monthAtPace: 'a month at this pace',
    note: (byPlay: boolean, shops: number, stock: string, value: string) =>
      `You only pay for ${byPlay ? 'plays that actually ran' : 'minutes actually shown'}. Your ${shops} ${plural(shops, 'shop holds', 'shops hold')} ${stock} ${byPlay ? 'plays' : 'minutes'} in this mix, worth ${value} a week in total.`,
    shapeTitle: 'What shape is your ad',
    shapeHint: 'The more of the board it takes, the more it costs.',
    perUnit: (unit: string) => `/ ${unit}`,
    billedOnPlays: ' Billed on plays, not minutes.',
    shapeFoot: 'Prices shown are peak; off-peak is about half. A short video is billed by the play because that is what you are buying: a count of fifteen-second runs, not a stretch of time.',
    whenTitle: 'When it runs',
    whenHint: 'Peak costs more. Pick any mix.',
    free: (n: string, unit: string) => `${n} ${unit} free`,
    setSpend: 'Set your weekly spend',
    spendLabel: 'Weekly spend',
    spendValue: (money: string, n: string, unit: string) => `${money} per week, ${n} ${unit}`,
    buysEvery: (money: string, unit: string) => `${money} buys every ${unit}`,
    full: 'That is the whole of these shops’ ad time for the week in this format. There is nothing more to sell until another screen joins.',
  },
  creative: {
    notImage: 'That file isn’t artwork we can play. Upload a PNG or JPG, or an MP4 for a video spot.',
    tooBig: 'That file is too big. Images go up to 6 MB, video up to 12 MB.',
    tooLong: 'A video spot runs 20 seconds or less. Trim it and try again.',
    uploading: 'Sending to the boards…',
    uploadFailed: 'That upload did not finish.',
    changeBack: ' Change the shape, or what it costs, back in step 01.',
    upload: 'Upload your ad',
    uploadedAlt: 'Your uploaded ad creative',
    placed: 'Placed in every preview below.',
    replace: 'Replace',
    remove: 'Remove',
    drop: 'Drop your artwork here',
    dropSub: 'or choose a file · PNG, JPG or MP4',
    previews: 'On the screens we run',
    previewsHint: (n: number, total: number) => `${n} of ${total} board types carry this format.`,
    yourAdHere: 'Your ad here',
    noFormat: 'Doesn’t carry this format',
    boardAlt: (name: string) => `${name} board`,
  },
  analytics: {
    tabs: { overview: 'Overview', where: 'Where it ran', when: 'When it ran', creative: 'Creative' },
    tabsLabel: 'Campaign reporting',
    spendToDate: 'Spend to date',
    bookedForWeek: 'Booked for the week',
    daysAt: (days: number, weekly: string) => `${days} ${plural(days, 'day', 'days')} · ${weekly} / wk`,
    nothingCharged: 'Nothing is charged until it plays',
    playsDelivered: 'Plays delivered',
    minutesOnScreen: 'Minutes on screen',
    ofScreenTime: (hours: string) => `${hours} of screen time`,
    playsOf15: (n: string) => `${n} plays of 0:15`,
    costPer: (unit: string) => `Cost per ${unit}`,
    aMinuteAPlay: (min: string, play: string) => `${min} a minute · ${play} a play`,
    heads: 'Heads past the board',
    perThousand: (n: string) => `${n} per thousand`,
    shops: 'Shops',
    screensAreas: (screens: number, areas: number) =>
      `${screens} ${plural(screens, 'screen', 'screens')} · ${areas} ${plural(areas, 'area', 'areas')}`,
    format: 'Format',
    billedBy: (unit: string) => `Billed by the ${unit}`,
    dayByDay: 'Day by day',
    weekAsBooked: 'The week as booked',
    busiest: (days: number, weekday: string, spend: string) => `${days} days · busiest was ${weekday} at ${spend}`,
    startsWhen: 'Starts the day the shop approves your creative',
    dailyCaption: (days: number) => `Daily spend across ${days} days, one bar a day.`,
    nothingPlayed: 'Nothing has played yet. This chart fills in from the first day the board runs your spot, one bar a day.',
    weeklyBudget: 'Weekly budget',
    perWeek: (unit: string) => `${unit} a week`,
    weeksRun: 'Weeks run',
    bestShop: 'Best shop',
    howTitle: 'How this is worked out',
    how1: (rate: string) => `Your week is spread across the shops you booked in proportion to what each one has to sell, then priced on the same rate card you saw when you booked: ${rate} a minute on this mix. Peak minutes cost more than the afternoon, so a campaign that skips the quiet hours buys fewer of them for the same money.`,
    how2: 'Heads past the board is a planning figure from each shop’s own footfall, pro-rated by the share of its open week your ad occupied. It is not a count of faces and nothing here measures attention.',
    everyScreen: 'Every screen it played on',
    shopsScreens: (shops: number, screens: number) =>
      `${shops} ${plural(shops, 'shop', 'shops')} · ${screens} ${plural(screens, 'screen', 'screens')}`,
    th: { shop: 'Shop', area: 'Area', screens: 'Screens', time: 'Time on screen', heads: 'Heads', rate: 'Rate', spend: 'Spend', share: 'Share of spend' },
    installing: 'Installing',
    onTheMap: 'On the map',
    reachPerDollar: 'Reach per dollar',
    headsPerDollar: 'heads / $',
    trimNote: 'Cheap minutes in a busy room go furthest. This is the order to trim from if the budget has to come down.',
    hourByHour: 'Hour by hour',
    hourSub: 'Minutes of screen time, across the shop day',
    hourCaption: 'Minutes of screen time by hour of the shop day.',
    hourTitle: (label: string, minutes: string) => `${label} · ${minutes} minutes`,
    hourNote: 'Every daypart you bought lands evenly across the hours it covers. Nothing here counts footfall by the hour, and a curve drawn from nothing would be a lie told in a prettier shape.',
    daypartCost: 'What each daypart cost',
    daypartSub: (bought: number, rate: string) => `${bought} of 3 bought · ${rate} a minute blended`,
    perMin: '/ min',
    costInShape: 'What it costs in this shape',
    rateOnMix: 'Rate on this mix',
    costOnePlay: 'Cost of one play',
    costHour: 'Cost of an hour on screen',
    monthAtPace: 'A month at this pace',
    shapeNote: ' Change the shape and the price moves with it: a strip under the menu is the least we ask the room for and the least we charge.',
    artwork: 'Artwork',
    onFile: 'Artwork on file',
    exampleNote: ' · shown on an example board to illustrate the slot. The boards you booked are not pictured.',
    boardAlt: (name: string) => `${name} board`,
    days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  flow: {
    title: 'How it works',
    nodes: [
      { title: 'Set your spend', note: 'Minutes, not impressions' },
      { title: 'Choose when', note: 'Peak costs more' },
      { title: 'Build your ad', note: 'Format and artwork' },
      { title: 'The shop owner reviews it', note: 'Their screen, their call' },
      { title: 'Your ad joins the rotation', note: 'In front of the whole room' },
      { title: 'You pay for minutes shown', note: 'The rest rolls over' },
    ],
    sample: { name: 'Mia’s Flower Bar', line: 'Bright stems for your table', where: 'Freedom Blvd & 700 North · open till 7' },
    branchBefore: 'Rejected? Swap the artwork and it comes straight back to ',
    branchStep: 'step 03',
    branchAfter: '. No charge for an ad that never ran.',
    timesPlays: 'Times it plays each week',
    minutesOnScreen: 'Minutes on screen each week',
    aWeekOnMix: (rate: string, unit: string) => ` a week · ${rate} a ${unit} on this mix`,
    drag: 'Drag to set a weekly spend',
    spendValue: (money: string, minutes: string) => `${money} a week, ${minutes} minutes on screen`,
    spendNote: (bannerOff: string, fullPeak: string) => `Two things set the price: how much of the board your ad takes, and when it runs. A strip under the menu starts at ${bannerOff} a minute; blanking the whole board at peak is ${fullPeak}. No auctions, no bidding against national brands for the shop down the street.`,
    whereNote: (city: string) => `AdBite is live in one shop in ${city} today, so “where” is a short list and “when” is the real choice. Lunch and dinner are peak because there is a queue in front of the board; the afternoon is about half the price. As shops join, this map and the builder fill in together.`,
    billedPerPlay: 'Billed per play rather than per minute, because a count of runs is what you are buying.',
    peakOff: (peak: string, off: string) => `${peak} a minute at peak, ${off} off-peak.`,
    uploadLands: ' Upload your own artwork in the builder and it lands in this exact slot.',
    reviewPending: 'The shop sees your ad before anyone else does. Try it from their side:',
    reject: 'Reject',
    approve: 'Approve',
    approved: 'Approved.',
    approvedText: ' It goes into the rotation on the next content push, and your minutes start counting from the first play.',
    tryOther: 'Try the other answer',
    rejected: 'Rejected.',
    rejectedText: ' Nothing runs, nothing is billed. You get the reason if the owner gives one, swap the artwork, and it returns to their queue.',
    backTo3: 'Back to step 03',
    tryAgain: 'Try again',
    onScreenNow: 'On screen now',
    you: 'You',
    liveNote: 'Your turn comes round every few minutes, every hour the shop is open, on the only screen in the room. Nobody scrolls past it, nobody blocks it, and nobody else is bidding for that second.',
    weekOf: (n: number) => `Week of Sep 8 · ${n} ${plural(n, 'shop', 'shops')}`,
    booked: (byPlay: boolean): string => (byPlay ? 'Plays booked' : 'Minutes booked'),
    ran: (byPlay: boolean): string => (byPlay ? 'Plays that ran' : 'Minutes actually shown'),
    rate: 'Rate',
    rolled: 'Unrun, rolled into next week',
    youPay: 'You pay',
    billNote: 'A play that never happened is never charged. Time on a screen, or runs of a video, counted by the player itself and reported back every week.',
    cta: 'Build yours, no account needed',
    ctaSub: (shops: number, screens: number, city: string) =>
      `${shops} ${plural(shops, 'shop', 'shops')} · ${screens} ${plural(screens, 'screen', 'screens')} in ${city}`,
  },
  tour: {
    label: 'Dashboard tour',
    pause: 'Pause the tour',
    play: 'Play the tour',
    open: 'Open it yourself',
    frames: [
      { tab: 'Pick the shops', title: 'Pick the shops, or draw the block.', note: 'Search the network, take a whole neighbourhood in one press, or circle a radius around your own front door and take everything inside it.' },
      { tab: 'Price the week', title: 'See the week before you buy it.', note: 'Shape, hours and spend on one screen. Move any of the three and the minutes, the rate and the monthly figure all move with it.' },
      { tab: 'Drop the artwork', title: 'Your artwork, in the slot it will occupy.', note: 'Drop in a PNG and it appears on every board type that carries your format, at the size and position it will actually run.' },
      { tab: 'Watch it run', title: 'Then watch what it does.', note: 'Spend to date, minutes on screen, cost per play and cost per thousand heads, with a bar for every day since the board started playing it.' },
      { tab: 'Where it ran', title: 'Down to the screen.', note: 'Every shop it played on, how long it held each one, what that shop cost and what share of the week it took.' },
      { tab: 'When it ran', title: 'And down to the hour.', note: 'Which dayparts you bought, what each was charged at, and where the minutes landed across the shop day.' },
    ],
  },
};

const es: typeof en = {
  dash: {
    steps: [
      { title: 'Ubícalo', note: 'Negocios, grupos y mapa' },
      { title: 'Ponle precio', note: 'Formato, horario y gasto' },
      { title: 'Créalo', note: 'Arte y vistas previas' },
    ],
    back: 'Panel',
    newCampaign: 'Nueva campaña',
    send: {
      title: 'Envíanoslo',
      hint: 'Lo recibe una persona, no una cola.',
      email: 'Tu correo',
      emailPlaceholder: 'tu@tunegocio.com',
      note: 'AdBite está en piloto, así que esto llega a info@adbite.site como solicitud, no como una reserva definitiva de la semana. No se cobra nada ahora, el dueño del negocio revisa tu anuncio antes de que se muestre, y solo pagas por lo que realmente se reproduce.',
      couldNotSave: 'No se pudo guardar la campaña',
    },
    bar: {
      perWeek: (unit: string) => `${unit} / semana`,
      spend: 'Gasto',
      shops: 'Negocios',
      format: 'Formato',
      rate: 'Tarifa',
      rateLine: (peak: string, off: string) => `${peak} pico · ${off} baja`,
      pickOne: 'Elige al menos un negocio.',
      upload: 'Sube tu arte para enviar.',
      addEmail: 'Agrega un correo para poder responderte.',
      back: 'Atrás',
      cancel: 'Cancelar',
      submit: 'Enviar a AdBite',
      next: 'Continuar',
    },
    status: { onScreen: 'En pantalla', inReview: 'En revisión con el negocio', sample: 'Ejemplo' },
    detail: {
      booked: (date: string) => `Reservado el ${date}`,
      playingSince: (date: string) => ` · en pantalla desde el ${date}`,
      delete: 'Eliminar',
      banner: 'Todavía no se ha reproducido nada, así que cada cifra de abajo es la semana que reservaste, no una semana que ocurrió. Los reportes cambian la primera vez que el tablero reproduce tu anuncio.',
    },
    head: {
      advertiser: 'Anunciante',
      title: 'Tus campañas',
      onScreen: 'En pantalla',
      weeklySpend: 'Gasto semanal',
      spentToDate: 'Gastado hasta hoy',
      minutesPerWeek: 'Minutos / semana',
      screensReachable: 'Pantallas disponibles',
    },
    list: {
      label: 'Tus campañas',
      meta: (shops: number, minutes: string, spent: string | null) =>
        `${shops} ${plural(shops, 'negocio', 'negocios')} · ${minutes} min / sem${spent ? ` · ${spent} gastados` : ''}`,
      removeSamples: 'Quitar los ejemplos',
    },
    empty: {
      title: 'Todavía no hay campañas.',
      text: (live: number, minutes: string, coming: number) =>
        `AdBite se está instalando en los condados de Salt Lake, Utah y Cache. Hoy ${live} ${plural(live, 'tablero está mostrando', 'tableros están mostrando')} anuncios, con ${minutes} minutos de tiempo de anuncios a la semana, y otros ${coming} negocios están en instalación y se pueden reservar por adelantado.`,
      samples: 'Cargar cuatro ejemplos',
      note: 'Reservas inventadas: tres con algunas semanas corridas para que los reportes tengan algo que mostrar, y una todavía esperando al dueño del negocio. Llevan la etiqueta Ejemplo en todos lados y se borran con un clic.',
    },
  },
  place: {
    tools: {
      pan: { label: 'Elegir', hint: 'Haz clic en un pin para agregar o quitar ese negocio' },
      radius: { label: 'Radio', hint: 'Presiona en el mapa y arrastra desde tu propia puerta' },
      lasso: { label: 'Dibujar zona', hint: 'Haz clic en las esquinas de una cuadra. Doble clic para cerrar' },
    },
    search: 'Busca negocios, calles, tipos de comida',
    searchLabel: 'Buscar en la red',
    clearSearch: 'Borrar búsqueda',
    neighbourhoods: 'Vecindarios',
    kinds: 'Tipos de negocio',
    chipTitle: (blurb: string, n: number) => `${blurb}. Clic para tomar los ${n}; shift + clic para filtrar la lista.`,
    shown: (visible: number, total: number) =>
      visible === total ? `${total} negocios` : `${visible} de ${total} mostrados`,
    selectShown: 'Seleccionar los mostrados',
    clear: 'Limpiar',
    resetFilters: 'Quitar filtros',
    nothingMatches: 'Nada coincide con eso.',
    whoTitle: 'A quién esperas llegar',
    whoNote: 'Una solicitud en la reserva, no una garantía de segmentación: una rotación, todo el local.',
    mapTools: 'Herramientas de selección en el mapa',
    undo: 'Deshacer',
    drawn: (shape: string, n: number) => `${shape} · ${n} ${plural(n, 'negocio agregado', 'negocios agregados')}`,
    radiusShape: (label: string) => `Radio de ${label}`,
    areaShape: (points: number) => `zona dibujada a mano, ${points} puntos`,
    foot: { shops: 'Negocios', of: (n: number) => ` de ${n}`, screens: 'Pantallas', minutes: 'Minutos a la semana', heads: 'Personas frente al tablero' },
    note: (live: number, chosen: number) =>
      `${live} de los ${chosen} ${plural(chosen, 'negocio', 'negocios')} que elegiste ${plural(live, 'está mostrando', 'están mostrando')} anuncios hoy. El resto son tableros que estamos instalando: viajan con tu solicitud y guardan tu lugar, y no se cobra nada por uno hasta que su pantalla esté encendida.`,
  },
  spend: {
    presets: [
      { label: 'Tardes', note: 'Los minutos más baratos' },
      { label: 'Hora del almuerzo', note: 'Pico, 11am-2pm' },
      { label: 'Hora de la cena', note: 'Pico, 5pm-9pm' },
      { label: 'Todo el horario', note: 'La semana completa' },
    ],
    weekdays: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
    eyebrowPlays: 'Veces que se reproduce tu anuncio, cada semana',
    eyebrowMinutes: 'Minutos que tu anuncio está en pantalla, cada semana',
    min: 'min',
    perWeekOnMix: (rate: string, unit: string) => `por semana · ${rate} por ${unit} en esta mezcla`,
    perDay: (unit: string) => `${unit} por día, a lo largo de la semana`,
    shut: 'cerrado',
    playsOf: 'reproducciones de un anuncio de 0:15',
    screenTime: 'de tiempo en pantalla a la semana',
    monthAtPace: 'al mes a este ritmo',
    note: (byPlay: boolean, shops: number, stock: string, value: string) =>
      `Solo pagas por ${byPlay ? 'las reproducciones que realmente ocurrieron' : 'los minutos realmente mostrados'}. ${plural(shops, 'Tu negocio tiene', `Tus ${shops} negocios tienen`)} ${stock} ${byPlay ? 'reproducciones' : 'minutos'} en esta mezcla, con un valor total de ${value} a la semana.`,
    shapeTitle: 'Qué forma tiene tu anuncio',
    shapeHint: 'Cuanto más tablero ocupa, más cuesta.',
    perUnit: (unit: string) => `/ ${unit}`,
    billedOnPlays: ' Se cobra por reproducciones, no por minutos.',
    shapeFoot: 'Los precios mostrados son de hora pico; la hora baja cuesta cerca de la mitad. Un video corto se cobra por reproducción porque eso es lo que compras: un número de reproducciones de quince segundos, no un tramo de tiempo.',
    whenTitle: 'Cuándo se muestra',
    whenHint: 'La hora pico cuesta más. Elige cualquier combinación.',
    free: (n: string, unit: string) => `${n} ${unit} libres`,
    setSpend: 'Define tu gasto semanal',
    spendLabel: 'Gasto semanal',
    spendValue: (money: string, n: string, unit: string) => `${money} por semana, ${n} ${unit}`,
    buysEvery: (money: string, unit: string) => `${money} compra cada ${unit}`,
    full: 'Ese es todo el tiempo de anuncios de estos negocios para la semana en este formato. No hay más que vender hasta que se sume otra pantalla.',
  },
  creative: {
    notImage: 'Ese archivo no es arte que podamos reproducir. Sube un PNG o JPG, o un MP4 para un anuncio en video.',
    tooBig: 'Ese archivo pesa demasiado. Las imágenes llegan a 6 MB y el video a 12 MB.',
    tooLong: 'Un anuncio en video dura 20 segundos o menos. Recórtalo e inténtalo de nuevo.',
    uploading: 'Enviando a los tableros…',
    uploadFailed: 'Esa subida no se completó.',
    changeBack: ' Cambia la forma, o lo que cuesta, en el paso 01.',
    upload: 'Sube tu anuncio',
    uploadedAlt: 'El anuncio que subiste',
    placed: 'Colocado en todas las vistas previas de abajo.',
    replace: 'Reemplazar',
    remove: 'Quitar',
    drop: 'Arrastra tu arte aquí',
    dropSub: 'o elige un archivo · PNG, JPG o MP4',
    previews: 'En las pantallas que operamos',
    previewsHint: (n: number, total: number) => `${n} de ${total} tipos de tablero aceptan este formato.`,
    yourAdHere: 'Tu anuncio aquí',
    noFormat: 'No acepta este formato',
    boardAlt: (name: string) => `Tablero de ${name}`,
  },
  analytics: {
    tabs: { overview: 'Resumen', where: 'Dónde se mostró', when: 'Cuándo se mostró', creative: 'Anuncio' },
    tabsLabel: 'Reportes de la campaña',
    spendToDate: 'Gastado hasta hoy',
    bookedForWeek: 'Reservado para la semana',
    daysAt: (days: number, weekly: string) => `${days} ${plural(days, 'día', 'días')} · ${weekly} / sem`,
    nothingCharged: 'No se cobra nada hasta que se reproduce',
    playsDelivered: 'Reproducciones entregadas',
    minutesOnScreen: 'Minutos en pantalla',
    ofScreenTime: (hours: string) => `${hours} de tiempo en pantalla`,
    playsOf15: (n: string) => `${n} reproducciones de 0:15`,
    costPer: (unit: string) => `Costo por ${unit}`,
    aMinuteAPlay: (min: string, play: string) => `${min} por minuto · ${play} por reproducción`,
    heads: 'Personas frente al tablero',
    perThousand: (n: string) => `${n} por mil`,
    shops: 'Negocios',
    screensAreas: (screens: number, areas: number) =>
      `${screens} ${plural(screens, 'pantalla', 'pantallas')} · ${areas} ${plural(areas, 'zona', 'zonas')}`,
    format: 'Formato',
    billedBy: (unit: string) => `Se cobra por ${unit}`,
    dayByDay: 'Día por día',
    weekAsBooked: 'La semana como se reservó',
    busiest: (days: number, weekday: string, spend: string) => `${days} días · el más activo fue ${weekday} con ${spend}`,
    startsWhen: 'Empieza el día que el negocio aprueba tu anuncio',
    dailyCaption: (days: number) => `Gasto diario en ${days} días, una barra por día.`,
    nothingPlayed: 'Todavía no se ha reproducido nada. Esta gráfica se llena desde el primer día que el tablero muestra tu anuncio, una barra por día.',
    weeklyBudget: 'Presupuesto semanal',
    perWeek: (unit: string) => `${unit} por semana`,
    weeksRun: 'Semanas corridas',
    bestShop: 'Mejor negocio',
    howTitle: 'Cómo se calcula esto',
    how1: (rate: string) => `Tu semana se reparte entre los negocios que reservaste en proporción a lo que cada uno tiene para vender, y luego se cobra con la misma tarifa que viste al reservar: ${rate} por minuto en esta mezcla. Los minutos de hora pico cuestan más que los de la tarde, así que una campaña que evita las horas tranquilas compra menos minutos con el mismo dinero.`,
    how2: 'Las personas frente al tablero son una cifra de planeación tomada del flujo de cada negocio, prorrateada por la parte de su semana abierta que ocupó tu anuncio. No es un conteo de caras y nada aquí mide atención.',
    everyScreen: 'Cada pantalla donde se mostró',
    shopsScreens: (shops: number, screens: number) =>
      `${shops} ${plural(shops, 'negocio', 'negocios')} · ${screens} ${plural(screens, 'pantalla', 'pantallas')}`,
    th: { shop: 'Negocio', area: 'Zona', screens: 'Pantallas', time: 'Tiempo en pantalla', heads: 'Personas', rate: 'Tarifa', spend: 'Gasto', share: 'Parte del gasto' },
    installing: 'En instalación',
    onTheMap: 'En el mapa',
    reachPerDollar: 'Alcance por dólar',
    headsPerDollar: 'personas / $',
    trimNote: 'Los minutos baratos en un local concurrido rinden más. Este es el orden para recortar si el presupuesto tiene que bajar.',
    hourByHour: 'Hora por hora',
    hourSub: 'Minutos de tiempo en pantalla, a lo largo del día del negocio',
    hourCaption: 'Minutos de tiempo en pantalla por hora del día del negocio.',
    hourTitle: (label: string, minutes: string) => `${label} · ${minutes} minutos`,
    hourNote: 'Cada franja horaria que compraste se reparte de forma pareja en las horas que cubre. Nada aquí cuenta el flujo por hora, y una curva dibujada de la nada sería una mentira con mejor forma.',
    daypartCost: 'Cuánto costó cada franja',
    daypartSub: (bought: number, rate: string) => `${bought} de 3 compradas · ${rate} por minuto en promedio`,
    perMin: '/ min',
    costInShape: 'Cuánto cuesta en esta forma',
    rateOnMix: 'Tarifa en esta mezcla',
    costOnePlay: 'Costo de una reproducción',
    costHour: 'Costo de una hora en pantalla',
    monthAtPace: 'Un mes a este ritmo',
    shapeNote: ' Cambia la forma y el precio cambia con ella: una franja debajo del menú es lo mínimo que le pedimos al local y lo mínimo que cobramos.',
    artwork: 'Arte',
    onFile: 'Arte en archivo',
    exampleNote: ' · mostrado en un tablero de ejemplo para ilustrar el espacio. Los tableros que reservaste no aparecen en la imagen.',
    boardAlt: (name: string) => `Tablero de ${name}`,
    days: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  },
  flow: {
    title: 'Cómo funciona',
    nodes: [
      { title: 'Define tu gasto', note: 'Minutos, no impresiones' },
      { title: 'Elige cuándo', note: 'La hora pico cuesta más' },
      { title: 'Crea tu anuncio', note: 'Formato y arte' },
      { title: 'El dueño lo revisa', note: 'Su pantalla, su decisión' },
      { title: 'Tu anuncio entra en rotación', note: 'Frente a todo el local' },
      { title: 'Pagas por minutos mostrados', note: 'El resto pasa a la siguiente semana' },
    ],
    sample: { name: 'Mia’s Flower Bar', line: 'Flores frescas para tu mesa', where: 'Freedom Blvd y 700 North · abierto hasta las 7' },
    branchBefore: '¿Rechazado? Cambia el arte y vuelve directo al ',
    branchStep: 'paso 03',
    branchAfter: '. Sin cargo por un anuncio que nunca se mostró.',
    timesPlays: 'Veces que se reproduce cada semana',
    minutesOnScreen: 'Minutos en pantalla cada semana',
    aWeekOnMix: (rate: string, unit: string) => ` a la semana · ${rate} por ${unit} en esta mezcla`,
    drag: 'Arrastra para definir un gasto semanal',
    spendValue: (money: string, minutes: string) => `${money} a la semana, ${minutes} minutos en pantalla`,
    spendNote: (bannerOff: string, fullPeak: string) => `Dos cosas definen el precio: cuánto tablero ocupa tu anuncio y cuándo se muestra. Una franja debajo del menú empieza en ${bannerOff} por minuto; apagar todo el tablero en hora pico cuesta ${fullPeak}. Sin subastas, sin competir contra marcas nacionales por el negocio de la esquina.`,
    whereNote: (city: string) => `Hoy AdBite está activo en un negocio en ${city}, así que “dónde” es una lista corta y “cuándo” es la verdadera decisión. El almuerzo y la cena son hora pico porque hay fila frente al tablero; la tarde cuesta cerca de la mitad. Conforme se sumen negocios, este mapa y el creador se llenan juntos.`,
    billedPerPlay: 'Se cobra por reproducción y no por minuto, porque un número de reproducciones es lo que compras.',
    peakOff: (peak: string, off: string) => `${peak} por minuto en hora pico, ${off} en hora baja.`,
    uploadLands: ' Sube tu propio arte en el creador y cae exactamente en este espacio.',
    reviewPending: 'El negocio ve tu anuncio antes que nadie. Pruébalo desde su lado:',
    reject: 'Rechazar',
    approve: 'Aprobar',
    approved: 'Aprobado.',
    approvedText: ' Entra en la rotación en la siguiente actualización, y tus minutos empiezan a contar desde la primera reproducción.',
    tryOther: 'Prueba la otra respuesta',
    rejected: 'Rechazado.',
    rejectedText: ' No se muestra nada y no se cobra nada. Recibes el motivo si el dueño lo da, cambias el arte, y vuelve a su cola.',
    backTo3: 'Volver al paso 03',
    tryAgain: 'Intentar de nuevo',
    onScreenNow: 'En pantalla ahora',
    you: 'Tú',
    liveNote: 'Tu turno vuelve cada pocos minutos, cada hora que el negocio está abierto, en la única pantalla del local. Nadie lo pasa de largo, nadie lo bloquea, y nadie más está pujando por ese segundo.',
    weekOf: (n: number) => `Semana del 8 de sep · ${n} ${plural(n, 'negocio', 'negocios')}`,
    booked: (byPlay: boolean) => (byPlay ? 'Reproducciones reservadas' : 'Minutos reservados'),
    ran: (byPlay: boolean) => (byPlay ? 'Reproducciones que ocurrieron' : 'Minutos realmente mostrados'),
    rate: 'Tarifa',
    rolled: 'No mostrado, pasa a la siguiente semana',
    youPay: 'Pagas',
    billNote: 'Una reproducción que nunca ocurrió nunca se cobra. Tiempo en una pantalla, o reproducciones de un video, contados por el propio reproductor y reportados cada semana.',
    cta: 'Crea la tuya, sin cuenta',
    ctaSub: (shops: number, screens: number, city: string) =>
      `${shops} ${plural(shops, 'negocio', 'negocios')} · ${screens} ${plural(screens, 'pantalla', 'pantallas')} en ${city}`,
  },
  tour: {
    label: 'Recorrido por el panel',
    pause: 'Pausar el recorrido',
    play: 'Reproducir el recorrido',
    open: 'Ábrelo tú mismo',
    frames: [
      { tab: 'Elige los negocios', title: 'Elige los negocios, o dibuja la cuadra.', note: 'Busca en la red, toma un vecindario entero con un clic, o traza un radio alrededor de tu propia puerta y toma todo lo que quede dentro.' },
      { tab: 'Calcula la semana', title: 'Mira la semana antes de comprarla.', note: 'Forma, horas y gasto en una sola pantalla. Mueve cualquiera de los tres y los minutos, la tarifa y la cifra mensual se mueven con ello.' },
      { tab: 'Sube el arte', title: 'Tu arte, en el espacio que va a ocupar.', note: 'Sube un PNG y aparece en cada tipo de tablero que acepta tu formato, con el tamaño y la posición reales.' },
      { tab: 'Míralo correr', title: 'Después mira qué hace.', note: 'Gasto hasta hoy, minutos en pantalla, costo por reproducción y costo por mil personas, con una barra por cada día desde que el tablero empezó a mostrarlo.' },
      { tab: 'Dónde se mostró', title: 'Hasta la pantalla.', note: 'Cada negocio donde se mostró, cuánto tiempo estuvo en cada uno, cuánto costó ese negocio y qué parte de la semana ocupó.' },
      { tab: 'Cuándo se mostró', title: 'Y hasta la hora.', note: 'Qué franjas compraste, cuánto se cobró cada una, y dónde cayeron los minutos a lo largo del día del negocio.' },
    ],
  },
};

export const CAMPAIGN = { en, es };
