/* The shop owner's landing page, plus the two illustrated blocks that only
 * appear on it: the four format previews and the board designer showcase. */

const en = {
  nav: { how: 'How it works', earnings: 'Earnings', tools: 'Menu tools' },
  ads: [
    { label: 'Now playing · Bottom banner', brand: 'Rosewood Barbers', detail: 'Walk-ins till seven · next door' },
    { label: 'Now playing · Full screen', brand: 'North Park Dental', detail: 'New patient checkups this week' },
    { label: 'Now playing · Short video', brand: 'Mia’s Flower Bar', detail: 'Bright stems · corner of 700 North' },
  ],
  hero: {
    title1: 'Your TV already runs your menu.',
    title2: 'Let it pay you, too.',
    lede: 'AdBite turns a slice of your screen into ad space for the businesses on your block. You approve every ad, you get paid every month, and the TV you already run starts paying for itself.',
    cta: 'Get your shop on AdBite',
    earnings: 'See what a screen earns',
  },
  how: {
    title: 'Five steps, then it runs itself.',
    lede: 'From the TV you already own to money in the account. Nothing here asks you to sell an ad, sign a contract, or hand over your screen.',
    steps: [
      ['Connect your screen', 'We help set up your existing TV or menu board.'],
      ['Advertisers book', 'Local businesses buy minutes on your screen, by the week.'],
      ['You approve', 'Review each creative. Approve or reject—nothing runs without you.'],
      ['Content stays yours', 'Ads take about a third of the screen. Your menu keeps the rest.'],
      ['Get paid', 'Your earnings land monthly, itemised by spot. No invoicing, no chasing.'],
    ] as [string, string][],
  },
  formats: {
    title: 'Four ways an ad can show up.',
    lede: 'Every format leaves your own content in place, and every format is subject to your approval.',
    banner: { title: 'Bottom banner', text: 'Your menu stays put. The strip below rotates between advertisers.' },
    rail: { title: 'Side rail', text: 'The right third, top to bottom. Your menu keeps the rest of the board.' },
    full: { title: 'Full-screen spot', text: 'Your board blanks for one turn of the rotation, then it is back.' },
    video: { title: 'Short video', text: 'Fifteen muted seconds on a blank board, then your menu is back. No sound to talk over.' },
    /* the ads drawn inside the previews */
    books: { name: 'Ninth Street Books', line: '10% off with your receipt', short: '10% off', sub: 'With your receipt' },
    barbers: { name: 'Rosewood Barbers', line: 'Walk-ins till seven', short: 'Walk-ins till 7', sub: 'Next door' },
    gym: { name: 'Iron Rose Gym', line: 'First class free', short: 'First class free', sub: 'Two blocks north' },
    cycles: { kicker: 'Local spot', name: 'Freedom Cycles', line: 'Free tune-up with any repair', sub: '820 N Freedom Blvd · two blocks north', back: 'Your menu is back in 0:04' },
    videoFrames: {
      muted: 'Muted',
      one: ['Iron Rose Gym', 'The strength room on your block'],
      two: ['First class free', 'Weekday mornings, no sign-up'],
      three: ['Two doors down', '214 N 400 W · open 5am to 10pm'],
    },
  },
  boards: {
    title: 'What it will look like.',
    lede: 'Four AdBite boards. Watch where the ad sits, and how much of the screen stays the shop’s.',
  },
  approval: {
    inReview: 'In review',
    queued: 'Queued today',
    brand: 'Rosewood Barbers',
    where: '4th & Pine · next door',
    headline: 'Walk-ins till seven',
    body: 'Fades, beard trims, hot-towel finish. No appointment, no wait list.',
    offer: '$5 off your first cut',
    format: 'Format',
    formatValue: 'Full-screen spot',
    length: 'Length',
    lengthValue: '15 seconds',
    rotation: 'Rotation',
    rotationValue: '6 turns an hour',
    runs: 'Runs',
    runsValue: 'Mon 15 Sep – Sun 21 Sep',
    reject: 'Reject',
    approve: 'Approve',
    yourCall: 'Your call',
    everyAd: 'Every ad gets your okay',
    title: 'Nothing runs without your approval.',
    lede: 'Every creative arrives in a quick review queue. If it doesn’t match your shop, your customers, or your values, reject it. No explanation needed.',
    points: ['See the ad before it’s scheduled', 'Approve or reject in one tap', 'Choose where on your screen ads sit'],
  },
  earnings: {
    title1: 'A little screen time.',
    title2: 'A meaningful extra.',
    note: (hours: string) => `Worked from a board like the ones going in now: open ${hours}, with about a third of the screen sold as ads. Your own hours change the number, and a second screen doubles it.`,
    points: {
      busy: 'Your busy hours are worth more, and are paid as such',
      upTo: (ceiling: string) => `Up to ${ceiling} a week when the bigger formats sell`,
      monthly: 'Paid monthly, itemised by spot',
      off: 'Turn ads off entirely any week you like',
    },
    calc: {
      minutes: 'Ad minutes on your board, each week',
      busy: 'Your busy hours · lunch and evening',
      quiet: 'The quiet middle · afternoons',
      paid: 'You are paid',
      perWeek: '/ week',
      perMonth: (n: string) => `${n} / month`,
      perYear: (n: string) => `About ${n} / year`,
    },
  },
  features: {
    title: 'And the controls that keep it yours.',
    lede: 'AdBite is the board software and the ad side together, so the tools that pay you are the same ones you use to run your menu. These are the levers on the paying half.',
    items: [
      ['Your ad share', 'Set how much of the screen ads can use, down to none at all this week. The rest is always your own content.'],
      ['Approval queue', 'Every creative waits for your yes. Reject anything that does not suit your shop, with no explanation owed.'],
      ['Screen check', 'We watch that your board is up and playing. If it drops off, you hear it from us first.'],
      ['Earnings, itemised', 'See what each spot paid and what is owed, then take your payment once a month.'],
    ] as [string, string][],
  },
  tools: {
    eyebrow: 'The other half of AdBite',
    title: 'Level up your menu.',
    lede: 'Ads are the part that pays. These are the tools that make the screen worth having in a week when nothing sells, and they come with it.',
    items: [
      ['Design the board itself', 'Drag your items around, set your prices, push it to the screen.'],
      ['Play your own food', 'Drop in video of the grill. A board that moves holds a queue.'],
      ['Put your reviews on the wall', 'Your best Google and Yelp lines, running between courses.'],
      ['Different menu, different hour', 'Breakfast, lunch, then the late board. Set it once.'],
    ] as [string, string][],
    showcase: {
      hour: 'Different menu, different hour',
      ground: 'And a ground that suits the room',
      note: 'Every item, price and section on that screen is typed in a browser and pushed to the TV. No design software, no waiting on anyone, no call-out fee. The striped block is where you are letting ads sit, and you pick the spot: a strip under the menu, a rail down the right, a full turn between boards, or nowhere at all.',
      cta: 'Design a board now',
    },
    tv: {
      title: 'No screen yet? We will bring one.',
      text: 'You do not need to buy a TV to start. We can supply the screen, mount it where your customers actually look, run the cable and set the board up on it. Tell us about your counter and we will tell you what it takes.',
      cta: 'Ask about a screen',
    },
  },
  venues: {
    title: 'For the places people return to.',
    restaurant: ['Restaurants', 'Make your menu board work a little harder between orders.'],
    barber: ['Barbers', 'Turn waiting-room watching into a local opportunity.'],
    salon: ['Salons & cosmetics', 'Keep your look and feel while earning from your screen.'],
    cafe: ['Cafés & more', 'Any independent shop with a TV is welcome.'],
  },
  join: {
    eyebrow: 'Pilot opening soon',
    title: 'Let your screen earn a little extra.',
    lede: 'Tell us about your shop. We’ll reach out when AdBite is ready in your area.',
    thinking: 'Already thinking about your screen?',
    thinkingBefore: 'See what the board tools can do in ',
    thinkingLink1: 'Level up your menu',
    thinkingMiddle: ', or look at the ad side from the buyer’s chair in the ',
    thinkingLink2: 'campaign builder',
    thinkingAfter: '.',
    form: {
      shop: 'Shop name',
      shopPlaceholder: 'Sunny Side Café',
      type: 'Shop type',
      typePlaceholder: 'Select type',
      types: ['Restaurant', 'Barber', 'Salon / cosmetics', 'Café', 'Other independent shop'],
      city: 'City',
      cityPlaceholder: 'Provo, UT',
      screens: '# of screens',
      screensPlaceholder: 'Choose',
      screenOptions: ['1', '2–3', '4+'],
      email: 'Your email',
      emailPlaceholder: 'you@yourshop.com',
      submit: 'Join the shop waitlist',
      onList: 'You’re on the list',
      thanks: 'Thanks. We’ll write from AdBite when we reach your city, and we will not pass your details to anyone.',
      quiet: 'No contract, no hardware to buy, and you can leave whenever you like.',
    },
  },
};

const es: typeof en = {
  nav: { how: 'Cómo funciona', earnings: 'Ganancias', tools: 'Tu menú' },
  ads: [
    { label: 'En pantalla · Franja inferior', brand: 'Rosewood Barbers', detail: 'Sin cita hasta las siete · aquí al lado' },
    { label: 'En pantalla · Pantalla completa', brand: 'North Park Dental', detail: 'Revisiones para pacientes nuevos esta semana' },
    { label: 'En pantalla · Video corto', brand: 'Mia’s Flower Bar', detail: 'Flores frescas · esquina de 700 North' },
  ],
  hero: {
    title1: 'Tu TV ya muestra tu menú.',
    title2: 'Deja que también te pague.',
    lede: 'AdBite convierte una parte de tu pantalla en espacio publicitario para los negocios de tu cuadra. Tú apruebas cada anuncio, cobras cada mes, y la TV que ya tienes empieza a pagarse sola.',
    cta: 'Suma tu negocio a AdBite',
    earnings: 'Mira cuánto gana una pantalla',
  },
  how: {
    title: 'Cinco pasos, y después funciona solo.',
    lede: 'De la TV que ya tienes a dinero en tu cuenta. Nada de esto te pide vender un anuncio, firmar un contrato ni entregar tu pantalla.',
    steps: [
      ['Conecta tu pantalla', 'Te ayudamos a configurar tu TV o tablero de menú actual.'],
      ['Los anunciantes reservan', 'Negocios locales compran minutos en tu pantalla, por semana.'],
      ['Tú apruebas', 'Revisa cada anuncio. Aprueba o rechaza: nada se muestra sin ti.'],
      ['El contenido sigue siendo tuyo', 'Los anuncios ocupan como un tercio de la pantalla. Tu menú se queda con el resto.'],
      ['Cobra', 'Tus ganancias llegan cada mes, detalladas por espacio. Sin facturar ni perseguir a nadie.'],
    ] as [string, string][],
  },
  formats: {
    title: 'Cuatro formas en que puede aparecer un anuncio.',
    lede: 'Todos los formatos dejan tu contenido en su lugar, y todos pasan por tu aprobación.',
    banner: { title: 'Franja inferior', text: 'Tu menú no se mueve. La franja de abajo rota entre anunciantes.' },
    rail: { title: 'Columna lateral', text: 'El tercio derecho, de arriba abajo. Tu menú se queda con el resto del tablero.' },
    full: { title: 'Pantalla completa', text: 'Tu tablero se apaga por un turno de la rotación, y luego vuelve.' },
    video: { title: 'Video corto', text: 'Quince segundos sin sonido en pantalla completa, y luego vuelve tu menú. Nada que interrumpa la conversación.' },
    books: { name: 'Ninth Street Books', line: '10% de descuento con tu recibo', short: '10% menos', sub: 'Con tu recibo' },
    barbers: { name: 'Rosewood Barbers', line: 'Sin cita hasta las siete', short: 'Sin cita hasta las 7', sub: 'Aquí al lado' },
    gym: { name: 'Iron Rose Gym', line: 'Primera clase gratis', short: 'Primera clase gratis', sub: 'Dos cuadras al norte' },
    cycles: { kicker: 'Anuncio local', name: 'Freedom Cycles', line: 'Afinación gratis con cualquier reparación', sub: '820 N Freedom Blvd · dos cuadras al norte', back: 'Tu menú vuelve en 0:04' },
    videoFrames: {
      muted: 'Sin sonido',
      one: ['Iron Rose Gym', 'El gimnasio de tu cuadra'],
      two: ['Primera clase gratis', 'Mañanas entre semana, sin registro'],
      three: ['Dos puertas más allá', '214 N 400 W · abierto de 5am a 10pm'],
    },
  },
  boards: {
    title: 'Así se va a ver.',
    lede: 'Cuatro tableros de AdBite. Fíjate dónde queda el anuncio y cuánta pantalla sigue siendo del negocio.',
  },
  approval: {
    inReview: 'En revisión',
    queued: 'Llegó hoy',
    brand: 'Rosewood Barbers',
    where: '4th & Pine · aquí al lado',
    headline: 'Sin cita hasta las siete',
    body: 'Degradados, barba, toalla caliente. Sin cita y sin lista de espera.',
    offer: '$5 de descuento en tu primer corte',
    format: 'Formato',
    formatValue: 'Pantalla completa',
    length: 'Duración',
    lengthValue: '15 segundos',
    rotation: 'Rotación',
    rotationValue: '6 turnos por hora',
    runs: 'Se muestra',
    runsValue: 'Lun 15 sep – Dom 21 sep',
    reject: 'Rechazar',
    approve: 'Aprobar',
    yourCall: 'Tú decides',
    everyAd: 'Cada anuncio pasa por tu aprobación',
    title: 'Nada se muestra sin tu aprobación.',
    lede: 'Cada anuncio llega a una cola de revisión rápida. Si no va con tu negocio, tus clientes o tus valores, recházalo. No hace falta explicar nada.',
    points: ['Mira el anuncio antes de que se programe', 'Aprueba o rechaza con un toque', 'Elige dónde van los anuncios en tu pantalla'],
  },
  earnings: {
    title1: 'Un poco de tiempo en pantalla.',
    title2: 'Un extra que se nota.',
    note: (hours: string) => `Calculado con un tablero como los que estamos instalando ahora: abierto ${hours}, con cerca de un tercio de la pantalla vendida como anuncios. Tu propio horario cambia la cifra, y una segunda pantalla la duplica.`,
    points: {
      busy: 'Tus horas más ocupadas valen más, y se pagan así',
      upTo: (ceiling: string) => `Hasta ${ceiling} a la semana cuando se venden los formatos grandes`,
      monthly: 'Pago mensual, detallado por espacio',
      off: 'Apaga los anuncios por completo cualquier semana',
    },
    calc: {
      minutes: 'Minutos de anuncios en tu tablero, cada semana',
      busy: 'Tus horas ocupadas · almuerzo y noche',
      quiet: 'La tarde tranquila',
      paid: 'Te pagamos',
      perWeek: '/ semana',
      perMonth: (n: string) => `${n} / mes`,
      perYear: (n: string) => `Cerca de ${n} / año`,
    },
  },
  features: {
    title: 'Y los controles que lo mantienen tuyo.',
    lede: 'AdBite es el software del tablero y la parte de anuncios juntos, así que las herramientas que te pagan son las mismas con las que manejas tu menú. Estas son las palancas de la mitad que paga.',
    items: [
      ['Tu espacio de anuncios', 'Decide cuánta pantalla pueden usar los anuncios, hasta nada esta semana. El resto siempre es tu contenido.'],
      ['Cola de aprobación', 'Cada anuncio espera tu sí. Rechaza lo que no vaya con tu negocio, sin deberle explicaciones a nadie.'],
      ['Monitoreo de pantalla', 'Vigilamos que tu tablero esté encendido y funcionando. Si se cae, te enteras primero por nosotros.'],
      ['Ganancias detalladas', 'Mira cuánto pagó cada espacio y cuánto se te debe, y cobra una vez al mes.'],
    ] as [string, string][],
  },
  tools: {
    eyebrow: 'La otra mitad de AdBite',
    title: 'Mejora tu menú.',
    lede: 'Los anuncios son la parte que paga. Estas son las herramientas que hacen que la pantalla valga la pena aun en una semana sin ventas, y vienen incluidas.',
    items: [
      ['Diseña el tablero', 'Mueve tus platillos, pon tus precios, mándalo a la pantalla.'],
      ['Muestra tu comida', 'Sube un video de la parrilla. Un tablero con movimiento retiene la fila.'],
      ['Tus reseñas en la pared', 'Tus mejores comentarios de Google y Yelp, entre platillo y platillo.'],
      ['Otro menú, otra hora', 'Desayuno, almuerzo y el tablero de la noche. Configúralo una vez.'],
    ] as [string, string][],
    showcase: {
      hour: 'Otro menú, otra hora',
      ground: 'Y un fondo que vaya con tu local',
      note: 'Cada platillo, precio y sección de esa pantalla se escribe en el navegador y se manda a la TV. Sin software de diseño, sin esperar a nadie, sin cobro por visita. El bloque rayado es donde dejas que vayan los anuncios, y tú eliges el lugar: una franja debajo del menú, una columna a la derecha, un turno completo entre tableros, o ningún lado.',
      cta: 'Diseña un tablero ahora',
    },
    tv: {
      title: '¿Todavía no tienes pantalla? Te la llevamos.',
      text: 'No necesitas comprar una TV para empezar. Podemos poner la pantalla, montarla donde tus clientes realmente miran, pasar el cable y dejar el tablero funcionando. Cuéntanos cómo es tu mostrador y te decimos qué se necesita.',
      cta: 'Pregunta por una pantalla',
    },
  },
  venues: {
    title: 'Para los lugares a los que la gente vuelve.',
    restaurant: ['Restaurantes', 'Haz que tu tablero de menú trabaje un poco más entre pedidos.'],
    barber: ['Barberías', 'Convierte la espera en una oportunidad local.'],
    salon: ['Salones y estética', 'Conserva tu estilo mientras tu pantalla te genera ingresos.'],
    cafe: ['Cafés y más', 'Cualquier negocio independiente con una TV es bienvenido.'],
  },
  join: {
    eyebrow: 'El piloto abre pronto',
    title: 'Deja que tu pantalla gane un extra.',
    lede: 'Cuéntanos de tu negocio. Te contactamos cuando AdBite esté listo en tu zona.',
    thinking: '¿Ya estás pensando en tu pantalla?',
    thinkingBefore: 'Mira lo que hacen las herramientas del tablero en ',
    thinkingLink1: 'Mejora tu menú',
    thinkingMiddle: ', o mira el lado de los anuncios desde la silla del comprador en el ',
    thinkingLink2: 'creador de campañas',
    thinkingAfter: '.',
    form: {
      shop: 'Nombre del negocio',
      shopPlaceholder: 'Café La Esquina',
      type: 'Tipo de negocio',
      typePlaceholder: 'Elige un tipo',
      types: ['Restaurante', 'Barbería', 'Salón / estética', 'Café', 'Otro negocio independiente'],
      city: 'Ciudad',
      cityPlaceholder: 'Provo, UT',
      screens: 'Número de pantallas',
      screensPlaceholder: 'Elige',
      screenOptions: ['1', '2–3', '4+'],
      email: 'Tu correo',
      emailPlaceholder: 'tu@tunegocio.com',
      submit: 'Únete a la lista de espera',
      onList: 'Ya estás en la lista',
      thanks: 'Gracias. Te escribimos desde AdBite cuando lleguemos a tu ciudad, y no compartimos tus datos con nadie.',
      quiet: 'Sin contrato, sin comprar equipo, y te puedes ir cuando quieras.',
    },
  },
};

export const HOME = { en, es };
