/* The shop owner's workspace: the board editor, the approval queue, what the
 * screen pays, and the TVs. The door in front of it is in shared.ts, because
 * both sides walk through the same one. */

const en = {
  head: {
    yourScreen: 'Your screen',
    onTheBoard: 'On the board',
    adsSit: 'Ads sit',
    waitingOnYou: 'Waiting on you',
    youArePaid: 'You are paid',
    perWeek: '/ wk',
    workspace: 'Shop workspace',
  },
  setup: {
    title: 'What is this screen for?',
    exampleLabel: 'For example',
    sourceTitle: 'How do you want to fill it?',
    sourceLede: 'Either way the ads you approve are mixed in, and either way you are paid the same.',
    change: 'Change what this screen is',
    back: 'Back',
  },
  media: {
    title: 'Your own media',
    lede: 'Your pictures and film, played in a loop on your screen and mixed with the ads you approve. Nobody reviews these and you are never charged for them.',
    add: 'Add a picture or video',
    dropSub: 'PNG, JPG or MP4 · up to 6 MB for a picture, 12 MB for video',
    uploading: 'Sending to your screens…',
    processing: 'Getting it ready for the TV…',
    processingNote: 'Video is re-encoded so every screen can play it. This takes a minute.',
    empty: 'Nothing here yet. Add a picture or a short film and it goes on the screen with your board.',
    remove: 'Remove',
    holdFor: 'Hold for',
    seconds: 'seconds',
    notMedia: 'That file is not a picture or a video we can play. Use a PNG, JPG or MP4.',
    tooBig: 'That file is too big. Pictures go up to 6 MB, video up to 12 MB.',
    failed: 'That upload did not finish.',
  },
  tabs: {
    board: 'Your board',
    ads: 'Ads waiting',
    money: 'What it pays',
    tvs: 'Your TVs',
  },
  editor: {
    whichBoard: 'Which board',
    sectionName: 'Section name',
    moveUp: 'Move section up',
    moveDown: 'Move section down',
    deleteSection: (title: string) => `Delete the ${title || 'untitled'} section`,
    reorder: (name: string) => `Reorder ${name || 'this item'}. Use the arrow keys.`,
    item: 'Item',
    itemName: 'Item name',
    description: 'Short description',
    itemDescription: 'Item description',
    price: 'Price',
    tag: 'Tag',
    remove: (name: string) => `Remove ${name || 'this item'}`,
    addItem: 'Add an item',
    addSection: 'Add a section',
  },
  shop: {
    title: 'The shop',
    hint: 'What sits along the top of every board',
    name: 'Name',
    tagline: 'Line underneath',
    taglinePlaceholder: 'What you sell, and where you are',
  },
  look: {
    title: 'How it looks',
    hint: 'Four grounds. Nothing else to design',
  },
  screen: {
    title: 'Which way is the TV hung?',
    hint: 'The preview and the ad slot follow it',
  },
  save: {
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    unsaved: 'Unsaved changes',
    failed: 'That did not save. Try again.',
    signedOut: 'Sign in to keep this board',
  },
  reviews: {
    title: 'Your reviews, on the wall',
    toggle: 'Show your reviews on the board',
    review: 'Review',
    quotePlaceholder: 'What they said',
    who: 'Who said it',
    namePlaceholder: 'Name',
    remove: 'Remove this review',
    add: 'Add a review',
    note: 'Paste your own from Google or Yelp. They run between boards, to a room that is already standing in your shop.',
  },
  clip: {
    title: 'Play your own food',
    toggle: 'Play your own clip between boards',
    choose: 'Choose a clip',
    spec: 'MP4, up to 8 MB. Muted, on a loop, between boards',
    notVideo: 'That file isn’t a video. An MP4 of your kitchen is ideal.',
    tooBig: 'That clip is over 8 MB. Trim it or export it smaller.',
  },
  reset: 'Start again from the example board',
  preview: {
    onTheWall: 'On the wall',
    updates: 'Updates as you type',
    where: 'Where ads sit on your screen',
    note: 'Nothing here is a contract. Pick nowhere for a week you want the whole screen, and your earnings for that week go to zero with it. Every ad still waits for your yes.',
  },
  queue: {
    title: 'Nothing plays until you say so.',
    lede: 'Every creative booked onto your board waits here. Reject anything that does not suit your shop, your customers or your values. No explanation is owed to anyone.',
    empty: 'Nothing is waiting on you. When an advertiser books your board, their artwork lands here first.',
    booked: (date: string) => `Booked ${date}`,
    format: 'Format',
    takes: 'Takes',
    from: 'From',
    anAdvertiser: 'an advertiser',
    theCreative: 'The creative',
    onFile: 'Artwork on file',
    reject: 'Reject',
    approve: 'Approve',
    decided: 'Already decided',
    onScreen: 'On your screen',
    rejected: 'Rejected',
  },
  money: {
    title: 'What the screen pays you.',
    lede: 'Worked from your own hours and where you are letting ads sit. Move that on the board tab and every figure here moves with it.',
    week: 'Paid each week',
    weekNote: 'Your spots, spread across the year',
    month: 'A month',
    monthNote: 'Paid once a month by bank transfer',
    year: 'A year, spots full',
    paid: 'Paid to you',
    paidNote: 'Settled by bank transfer as invoices clear',
    minutes: 'Video minutes you are offering',
    minutesNote: (placement: string) => `${placement}, across your open week`,
    where: 'What video adds, hour by hour',
    note: 'The figures above are your permanent spots, which do not move with your week. This is the video on top of them: minutes of your screen sold by the hour, paid on what actually ran.',
    bank: {
      title: 'Where we send it',
      hint: 'A bank transfer, once a month',
      holder: 'Name on the account',
      holderPlaceholder: 'Bao Pao Wow LLC',
      routing: 'Routing number',
      account: 'Account number',
      type: 'Account type',
      checking: 'Checking',
      savings: 'Savings',
      save: 'Save these details',
      saving: 'Saving…',
      saved: (last4: string) => `Paid to the account ending ${last4}.`,
      change: 'Change',
      note: 'We send an ACH credit once a month and a note itemising it. We never take anything from this account, and the number is stored where nobody but the transfer can read it.',
      missing: 'Add your bank details and we can pay you. Until then your earnings sit here and nothing is lost.',
    },
    eitherWay: 'The screen earns either way.',
    eitherWayText: 'The board tools are yours whether or not a single ad sells this week. Design it, change it at lunch, put your reviews on it. The ads are the part that pays; the board is the part that works.',
  },
  tvs: {
    title: 'Your TVs.',
    lede: (minutes: number) => `Open the AdBite Board channel on a Roku and it shows a six-character code. Type it here and that screen is yours. Every TV checks for changes every ${minutes} minutes, so a menu edit or an approved ad takes up to ${minutes} minutes to reach the wall.`,
    code: 'Code on the TV',
    callIt: 'Call it',
    callItPlaceholder: 'Counter TV',
    pairing: 'Pairing…',
    pair: 'Pair this TV',
    paired: 'Paired. Your board is on it within a minute.',
    none: 'No TVs yet. Pair the first one above.',
    rename: 'Double-click to rename',
    onTheWall: 'On the wall',
    notCheckingIn: 'Not checking in',
    lastSeen: 'Last checked in',
    storage: 'Storage used',
    storageValue: (used: number, free: number | null) =>
      free === null ? `${used} MB of spots` : `${used} MB of spots · ${free} MB free`,
    never: 'Never',
    shows: 'Shows',
    adsOnly: 'Ads only (second screen)',
    menuAndAds: 'Your menu and ads',
    channel: 'Channel',
    unknown: 'unknown',
  },
};

const es: typeof en = {
  head: {
    yourScreen: 'Tu pantalla',
    onTheBoard: 'En el tablero',
    adsSit: 'Anuncios en',
    waitingOnYou: 'Esperándote',
    youArePaid: 'Te pagamos',
    perWeek: '/ sem',
    workspace: 'Espacio del negocio',
  },
  setup: {
    title: '¿Para qué es esta pantalla?',
    exampleLabel: 'Por ejemplo',
    sourceTitle: '¿Cómo quieres llenarla?',
    sourceLede: 'En ambos casos se mezclan los anuncios que apruebes, y en ambos se te paga igual.',
    change: 'Cambiar para qué es esta pantalla',
    back: 'Atrás',
  },
  media: {
    title: 'Tu propio contenido',
    lede: 'Tus fotos y videos, en bucle en tu pantalla y mezclados con los anuncios que apruebes. Nadie los revisa y nunca se te cobra por ellos.',
    add: 'Agregar una foto o un video',
    dropSub: 'PNG, JPG o MP4 · hasta 6 MB por foto, 12 MB por video',
    uploading: 'Enviando a tus pantallas…',
    processing: 'Preparándolo para la TV…',
    processingNote: 'El video se reconvierte para que toda pantalla pueda reproducirlo. Tarda un minuto.',
    empty: 'Aquí no hay nada todavía. Agrega una foto o un video corto y saldrá en la pantalla junto a tu tablero.',
    remove: 'Quitar',
    holdFor: 'Mantener',
    seconds: 'segundos',
    notMedia: 'Ese archivo no es una foto ni un video que podamos reproducir. Usa PNG, JPG o MP4.',
    tooBig: 'Ese archivo pesa demasiado. Las fotos llegan a 6 MB y el video a 12 MB.',
    failed: 'Esa subida no se completó.',
  },
  tabs: {
    board: 'Tu tablero',
    ads: 'Anuncios en espera',
    money: 'Cuánto paga',
    tvs: 'Tus TVs',
  },
  editor: {
    whichBoard: 'Qué tablero',
    sectionName: 'Nombre de la sección',
    moveUp: 'Subir sección',
    moveDown: 'Bajar sección',
    deleteSection: (title: string) => `Eliminar la sección ${title || 'sin nombre'}`,
    reorder: (name: string) => `Reordenar ${name || 'este platillo'}. Usa las flechas.`,
    item: 'Platillo',
    itemName: 'Nombre del platillo',
    description: 'Descripción corta',
    itemDescription: 'Descripción del platillo',
    price: 'Precio',
    tag: 'Etiqueta',
    remove: (name: string) => `Quitar ${name || 'este platillo'}`,
    addItem: 'Agregar un platillo',
    addSection: 'Agregar una sección',
  },
  shop: {
    title: 'El negocio',
    hint: 'Lo que va en la parte de arriba de cada tablero',
    name: 'Nombre',
    tagline: 'Línea de abajo',
    taglinePlaceholder: 'Qué vendes y dónde estás',
  },
  look: {
    title: 'Cómo se ve',
    hint: 'Cuatro fondos. Nada más que diseñar',
  },
  screen: {
    title: '¿Cómo está colgada la TV?',
    hint: 'La vista previa y el espacio del anuncio lo siguen',
  },
  save: {
    save: 'Guardar',
    saving: 'Guardando…',
    saved: 'Guardado',
    unsaved: 'Cambios sin guardar',
    failed: 'No se guardó. Inténtalo de nuevo.',
    signedOut: 'Inicia sesión para conservar este tablero',
  },
  reviews: {
    title: 'Tus reseñas, en la pared',
    toggle: 'Mostrar tus reseñas en el tablero',
    review: 'Reseña',
    quotePlaceholder: 'Lo que dijeron',
    who: 'Quién lo dijo',
    namePlaceholder: 'Nombre',
    remove: 'Quitar esta reseña',
    add: 'Agregar una reseña',
    note: 'Copia las tuyas de Google o Yelp. Se muestran entre tableros, a gente que ya está parada en tu negocio.',
  },
  clip: {
    title: 'Muestra tu comida',
    toggle: 'Reproducir tu propio video entre tableros',
    choose: 'Elige un video',
    spec: 'MP4, hasta 8 MB. Sin sonido, en bucle, entre tableros',
    notVideo: 'Ese archivo no es un video. Lo ideal es un MP4 de tu cocina.',
    tooBig: 'Ese video pesa más de 8 MB. Recórtalo o expórtalo más pequeño.',
  },
  reset: 'Empezar de nuevo desde el tablero de ejemplo',
  preview: {
    onTheWall: 'En la pared',
    updates: 'Se actualiza mientras escribes',
    where: 'Dónde van los anuncios en tu pantalla',
    note: 'Nada de esto es un contrato. Elige “ningún lado” en una semana en que quieras toda la pantalla, y tus ganancias de esa semana bajan a cero. Cada anuncio sigue esperando tu sí.',
  },
  queue: {
    title: 'Nada se muestra hasta que tú lo digas.',
    lede: 'Cada anuncio reservado para tu tablero espera aquí. Rechaza lo que no vaya con tu negocio, tus clientes o tus valores. No le debes explicaciones a nadie.',
    empty: 'No hay nada esperándote. Cuando un anunciante reserve tu tablero, su anuncio llega aquí primero.',
    booked: (date: string) => `Reservado el ${date}`,
    format: 'Formato',
    takes: 'Ocupa',
    from: 'De',
    anAdvertiser: 'un anunciante',
    theCreative: 'El anuncio',
    onFile: 'Arte en archivo',
    reject: 'Rechazar',
    approve: 'Aprobar',
    decided: 'Ya decididos',
    onScreen: 'En tu pantalla',
    rejected: 'Rechazado',
  },
  money: {
    title: 'Cuánto te paga la pantalla.',
    lede: 'Calculado con tu propio horario y con dónde dejas que vayan los anuncios. Cambia eso en la pestaña del tablero y todas las cifras de aquí cambian con ello.',
    week: 'Pago por semana',
    weekNote: 'Tus espacios, repartidos en el año',
    month: 'Un mes',
    monthNote: 'Se paga una vez al mes por transferencia',
    year: 'Un año, con los espacios llenos',
    paid: 'Pagado a ti',
    paidNote: 'Se liquida por transferencia cuando se cobran las facturas',
    minutes: 'Minutos de video que ofreces',
    minutesNote: (placement: string) => `${placement}, en toda tu semana abierta`,
    where: 'Lo que suma el video, hora por hora',
    note: 'Las cifras de arriba son tus espacios permanentes, que no cambian con tu semana. Esto es el video encima de ellos: minutos de tu pantalla vendidos por hora, pagados por lo que realmente se mostró.',
    bank: {
      title: 'A dónde te lo mandamos',
      hint: 'Una transferencia bancaria, una vez al mes',
      holder: 'Nombre en la cuenta',
      holderPlaceholder: 'Bao Pao Wow LLC',
      routing: 'Número de ruta',
      account: 'Número de cuenta',
      type: 'Tipo de cuenta',
      checking: 'Corriente',
      savings: 'Ahorros',
      save: 'Guardar estos datos',
      saving: 'Guardando…',
      saved: (last4: string) => `Se paga a la cuenta que termina en ${last4}.`,
      change: 'Cambiar',
      note: 'Mandamos una transferencia ACH una vez al mes y una nota con el detalle. Nunca sacamos nada de esta cuenta, y el número se guarda donde nadie salvo la transferencia puede leerlo.',
      missing: 'Agrega tus datos bancarios y te podemos pagar. Mientras tanto tus ganancias se quedan aquí y no se pierde nada.',
    },
    eitherWay: 'La pantalla gana de cualquier forma.',
    eitherWayText: 'Las herramientas del tablero son tuyas aunque no se venda ni un anuncio esta semana. Diséñalo, cámbialo al mediodía, ponle tus reseñas. Los anuncios son la parte que paga; el tablero es la parte que trabaja.',
  },
  tvs: {
    title: 'Tus TVs.',
    lede: (minutes: number) => `Abre el canal AdBite Board en un Roku y verás un código de seis caracteres. Escríbelo aquí y esa pantalla es tuya. Cada TV revisa si hay cambios cada ${minutes} minutos, así que un cambio en el menú o un anuncio aprobado tarda hasta ${minutes} minutos en llegar a la pared.`,
    code: 'Código en la TV',
    callIt: 'Ponle nombre',
    callItPlaceholder: 'TV del mostrador',
    pairing: 'Vinculando…',
    pair: 'Vincular esta TV',
    paired: 'Vinculada. Tu tablero aparece en ella en menos de un minuto.',
    none: 'Todavía no hay TVs. Vincula la primera arriba.',
    rename: 'Doble clic para renombrar',
    onTheWall: 'En la pared',
    notCheckingIn: 'Sin reportarse',
    lastSeen: 'Último reporte',
    storage: 'Almacenamiento',
    storageValue: (used: number, free: number | null) =>
      free === null ? `${used} MB en anuncios` : `${used} MB en anuncios · ${free} MB libres`,
    never: 'Nunca',
    shows: 'Muestra',
    adsOnly: 'Solo anuncios (segunda pantalla)',
    menuAndAds: 'Tu menú y anuncios',
    channel: 'Canal',
    unknown: 'desconocido',
  },
};

export const SHOP = { en, es };
