/* The board's lettering, as files a TV can open.
 *
 * A Roku draws text with a Font node, and a Font node takes a `uri` — so a
 * board set in Playfair can be drawn in Playfair on the wall, but only if the
 * TTF is somewhere the device can fetch it and verify it. That is what this
 * file is: the two weights of each face, on the shop assets origin, with the
 * hash and size the channel checks before it draws a single word.
 *
 * It is generated by `scripts/board-fonts.mjs`, which fetches the faces from
 * Google Fonts, uploads them to R2 and rewrites the table below. Do not edit
 * the table by hand — a wrong byte count here is a board that silently falls
 * back to the system font on every TV at once.
 *
 * Two weights per face and no more. The board uses bold for the shop name,
 * the section headings, the dish names and the prices, and regular for
 * everything else; a third weight would be another 300KB on every screen for
 * a difference nobody reads from eight feet away.
 *
 * Pure and DOM-free: lib/compose.ts imports it.
 */

import type { FontId } from './fonts.js';

export type FontFile = { src: string; sha256: string; bytes: number };
export type FontFiles = { regular: FontFile; bold: FontFile };

/* Faces with no entry are drawn in the device's own system font, which is
   what every board did before this existed and is a perfectly good menu
   board. `sans` is deliberately absent: it *is* the system font. */
export const BOARD_FONTS: Partial<Record<FontId, FontFiles>> = {
  inter: {
    regular: { src: 'https://assets.adbite.site/fonts/1b08e7fc267a5c7e1d614100f604b83e7e8a0be241f0f288faa2b3ac93a683ba.ttf', sha256: '1b08e7fc267a5c7e1d614100f604b83e7e8a0be241f0f288faa2b3ac93a683ba', bytes: 324820 },
    bold: { src: 'https://assets.adbite.site/fonts/eec66af7f2337bd34fe6e801cf92ededcb57a20c0d7bc40a61d4eefcbe3dd40c.ttf', sha256: 'eec66af7f2337bd34fe6e801cf92ededcb57a20c0d7bc40a61d4eefcbe3dd40c', bytes: 327324 },
  },
  archivo: {
    regular: { src: 'https://assets.adbite.site/fonts/01170409e32e22123a354fbaa7dcb5ca5300790bb77c05d569ec8fdc394e78c9.ttf', sha256: '01170409e32e22123a354fbaa7dcb5ca5300790bb77c05d569ec8fdc394e78c9', bytes: 110708 },
    bold: { src: 'https://assets.adbite.site/fonts/745c7f810c448f256b66e1beaf8d6ccc2be98c01e531a1da8b1e8cf805a5b857.ttf', sha256: '745c7f810c448f256b66e1beaf8d6ccc2be98c01e531a1da8b1e8cf805a5b857', bytes: 111948 },
  },
  bebas: {
    regular: { src: 'https://assets.adbite.site/fonts/939fea723dad24504f40faadc34eeffadfbbee558754f70c3c736e13786b0ab6.ttf', sha256: '939fea723dad24504f40faadc34eeffadfbbee558754f70c3c736e13786b0ab6', bytes: 56136 },
    bold: { src: 'https://assets.adbite.site/fonts/939fea723dad24504f40faadc34eeffadfbbee558754f70c3c736e13786b0ab6.ttf', sha256: '939fea723dad24504f40faadc34eeffadfbbee558754f70c3c736e13786b0ab6', bytes: 56136 },
  },
  oswald: {
    regular: { src: 'https://assets.adbite.site/fonts/bd6ff5a83bcdc92d7aac6dbb16e4dd2b0b0320bec6402bb81f5dd9735b500e46.ttf', sha256: 'bd6ff5a83bcdc92d7aac6dbb16e4dd2b0b0320bec6402bb81f5dd9735b500e46', bytes: 86068 },
    bold: { src: 'https://assets.adbite.site/fonts/a6ee8b91ec269a6f48631ba4ba1a3ab7e5039e5482dda8dc9672ee4620d7bd68.ttf', sha256: 'a6ee8b91ec269a6f48631ba4ba1a3ab7e5039e5482dda8dc9672ee4620d7bd68', bytes: 86416 },
  },
  space: {
    regular: { src: 'https://assets.adbite.site/fonts/ec926d5065eaca49a48f96e312bbae0bbc5733c24215cf5dfabbdccee926fef7.ttf', sha256: 'ec926d5065eaca49a48f96e312bbae0bbc5733c24215cf5dfabbdccee926fef7', bytes: 69360 },
    bold: { src: 'https://assets.adbite.site/fonts/3e756954468ff1cb302dae0414262e72f76a67d87bef3fa1f3226cd0fb9b2d85.ttf', sha256: '3e756954468ff1cb302dae0414262e72f76a67d87bef3fa1f3226cd0fb9b2d85', bytes: 69308 },
  },
  work: {
    regular: { src: 'https://assets.adbite.site/fonts/a131e7022b34ef1950a9d6bdda16f5d4509cc1fe1af5991a4552febd2a4027e5.ttf', sha256: 'a131e7022b34ef1950a9d6bdda16f5d4509cc1fe1af5991a4552febd2a4027e5', bytes: 114144 },
    bold: { src: 'https://assets.adbite.site/fonts/6debb300d1ba977250e6ddce0e6fe35607d9d5f4f6e0ae57ce5eb7505279fe2f.ttf', sha256: '6debb300d1ba977250e6ddce0e6fe35607d9d5f4f6e0ae57ce5eb7505279fe2f', bytes: 116972 },
  },
  playfair: {
    regular: { src: 'https://assets.adbite.site/fonts/1609a54fa3ad1abc8d0037132f73700333241ea0b65672079998e352f151dea7.ttf', sha256: '1609a54fa3ad1abc8d0037132f73700333241ea0b65672079998e352f151dea7', bytes: 123240 },
    bold: { src: 'https://assets.adbite.site/fonts/71a599c413e0126bb042a4b757adaf801fa8b67cdbbcc9cb42da427d7c3c5533.ttf', sha256: '71a599c413e0126bb042a4b757adaf801fa8b67cdbbcc9cb42da427d7c3c5533', bytes: 123608 },
  },
  dmserif: {
    regular: { src: 'https://assets.adbite.site/fonts/c03775f8cc3db88cfea259b231abe13f94e6a3d3cb01c09477a2e42a1f5919e1.ttf', sha256: 'c03775f8cc3db88cfea259b231abe13f94e6a3d3cb01c09477a2e42a1f5919e1', bytes: 70348 },
    bold: { src: 'https://assets.adbite.site/fonts/c03775f8cc3db88cfea259b231abe13f94e6a3d3cb01c09477a2e42a1f5919e1.ttf', sha256: 'c03775f8cc3db88cfea259b231abe13f94e6a3d3cb01c09477a2e42a1f5919e1', bytes: 70348 },
  },
  lora: {
    regular: { src: 'https://assets.adbite.site/fonts/1d37d1e34c77be80f0119754ad78df9aad30d5b1c78132a4cbdac0fe567f5d4f.ttf', sha256: '1d37d1e34c77be80f0119754ad78df9aad30d5b1c78132a4cbdac0fe567f5d4f', bytes: 132188 },
    bold: { src: 'https://assets.adbite.site/fonts/ac3145cd8846b6ab3522ac0579a4f5378271f6a93896cb800d27f301fa9f7758.ttf', sha256: 'ac3145cd8846b6ab3522ac0579a4f5378271f6a93896cb800d27f301fa9f7758', bytes: 132124 },
  },
  baskerville: {
    regular: { src: 'https://assets.adbite.site/fonts/f5bc4341f15de5e877d8d95b6b14b33e9a3da1f8fef4ed0700ed407f096cffb6.ttf', sha256: 'f5bc4341f15de5e877d8d95b6b14b33e9a3da1f8fef4ed0700ed407f096cffb6', bytes: 106728 },
    bold: { src: 'https://assets.adbite.site/fonts/8b008ffdae31b314657cb8e28d822da09893035d06bad9b1ab53ea762549cbd1.ttf', sha256: '8b008ffdae31b314657cb8e28d822da09893035d06bad9b1ab53ea762549cbd1', bytes: 106752 },
  },
  caveat: {
    regular: { src: 'https://assets.adbite.site/fonts/012f33f9814bf9614973983335c3a375fe267c094e7c09a02a276cd1dcd4180a.ttf', sha256: '012f33f9814bf9614973983335c3a375fe267c094e7c09a02a276cd1dcd4180a', bytes: 251024 },
    bold: { src: 'https://assets.adbite.site/fonts/f4365d9874c1b64026aca48786cf835a5decf2c740c06de04dbb05ce8c93ff37.ttf', sha256: 'f4365d9874c1b64026aca48786cf835a5decf2c740c06de04dbb05ce8c93ff37', bytes: 251256 },
  },
};

export function filesFor(id: FontId | null | undefined): FontFiles | null {
  if (!id) return null;
  return BOARD_FONTS[id] ?? null;
}
