import { createClient } from "@supabase/supabase-js";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
const file = readFileSync("roku/ads/rosas-spot.mp4");
const sha = createHash("sha256").update(file).digest("hex");
const key = `creatives/${sha}.mp4`;
const s3 = new S3Client({ region: "auto", endpoint: `https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`, credentials: { accessKeyId: process.env.R2_ACCESS_KEY_ID, secretAccessKey: process.env.R2_SECRET_ACCESS_KEY } });
await s3.send(new PutObjectCommand({ Bucket: process.env.R2_BUCKET, Key: key, Body: file, ContentType: "video/mp4", CacheControl: "public, max-age=31536000, immutable" }));
console.log("uploaded", key, file.length, "bytes");
const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const seedEmail = process.env.SEED_ADVERTISER_EMAIL;
if (!seedEmail) throw new Error("Set SEED_ADVERTISER_EMAIL to the advertiser account to seed against");
const { data: acct } = await admin.from("accounts").select("id, email").eq("email", seedEmail).single();
const { data: shop } = await admin.from("shops").select("id").eq("venue_id", "thai-papaya").single();
const { data: cr } = await admin.from("creatives").insert({ advertiser_id: acct.id, kind: "video", name: "rosas-spot.mp4", storage_path: key, bytes: file.length, sha256: sha, width: 960, height: 540, seconds: 15, ready: true }).select("id").single();
const { data: camp } = await admin.from("campaigns").insert({ advertiser_id: acct.id, name: "Rosa's Taqueria video (seed)", format: "video", venues: ["thai-papaya"], dayparts: ["lunch", "evening"], weekly_spend: 45, creative_id: cr.id, creative_name: "rosas-spot.mp4", email: acct.email, status: "live" }).select("id").single();
await admin.from("approvals").insert({ campaign_id: camp.id, shop_id: shop.id, status: "approved", decided_at: new Date().toISOString() });
console.log("campaign", camp.id, "approved for shop", shop.id);
console.log("url https://assets.adbite.site/" + key);
